### ISSUE TITLE
Can't stream

### ISSUE THREAD

**Issue by ghost** [TheBeastLT/torrentio-scraper#10]
Hey,

I make use of both Real-Debrid and AllDebrid, but I’m getting no cached links with AllDebrid while they are definitely cached on the service.

Can't stream at all either it just keeps loading this is the only addon that does this

**Edit:**
Seems like the no link part fixed itself, streaming still doesn't work though

**Comment by TheBeastLT** [comment]
There were some issues with the proxies, which are used when making requests for debrid providers. I've updated the them so should be working now. Let me know if you still have issues.
