### ISSUE TITLE
Torrentio not showing in Stremio Android version

### ISSUE THREAD

**Issue by onlytanmoy** [TheBeastLT/torrentio-scraper#100]
Hi @TheBeastLT sorry if I sound dim but I am unable to find Torrentio in my Android Stremio. I can install it in my Windows version of Stremio via https://torrentio.strem.fun/configure
Even though I am logged into both Stremio using the same account somehow Torrentio doesn't sync up and is absent in android version. Not sure what I am doing wrong, some guidance please.

**Comment by TheBeastLT** [comment]
Hi, this is not related to the addon itself and has to be some misunderstanding/misconfiguration on your side. Please do not open such issues here.
Check that you're using the same account on both platforms, and on android version make sure you're checking `Installed` addons section.

**Comment by onlytanmoy** [comment]
@TheBeastLT Thanks for your response and apologies for the misunderstanding.
I am keep to know how do I use your torrentio-scraper? I don't see anything under Releases section :(
Is it an apk or something else? If you can please drop some quick instructions on using it.

**Comment by TheBeastLT** [comment]
This is not a standalone application. It's an API deployed on a server to be used as an addon in Stremio.

**Comment by onlytanmoy** [comment]
Nice, thanks for the clarification mate.
