### ISSUE TITLE
Can you add Chinese providers? 

### ISSUE THREAD

**Issue by shanyan-wcx** [TheBeastLT/torrentio-scraper#101]
Such as https://share.dmhy.org/ and https://mikanani.me/, they have unique content.

**Comment by TheBeastLT** [comment]
Hi, anime is notoriously hard to index correctly, and many times needs some manual validation from time to time, so I don't want to add too much of it.
Also I see that some titles only have the Chinese name, which would make indexing impossible to match to a kitsu id.
