### ISSUE TITLE
Wrong episodes

### ISSUE THREAD

**Issue by VanHoevenTR** [TheBeastLT/torrentio-scraper#102]
The episodes of Ghost adventures shown out of order by one episode. For example episode 23 has the titles of episode 22 and so on. I checked IMDB and Wikipedia to make sure the episodes list are correct, they all are. Can it be fixed?

https://user-images.githubusercontent.com/70694330/218153182-a4c2670b-cfec-4af6-bb71-97fb457333cd.mp4

**Comment by TheBeastLT** [comment]
Didn't understand your issue, in the video everything seems fine. But nevertheless, episode is automatically parsed from the torrent name, so whatever the uploaded named the torrent that will be used to determine the episode.
