### ISSUE TITLE
[Request] New spanish providers

### ISSUE THREAD

**Issue by K0rat** [TheBeastLT/torrentio-scraper#104]
Hey,

I know that Torrentio has many english and portuguese providers, however there is only one spanish (Mejor Torrent). It would be very interesting if you could add the following spanish public providers because they are very famous and they have a lot of content in spanish:

Don Torrent
Gran Torrent
Elite Torrent

I hope you consider my request and add them. Thank you very much in advance.

**Comment by TheBeastLT** [comment]
From what I've looked many torrents overlap from these websites and `MejorTorrent` is the one that had the most content and is well structured and maintained compared to other. At this time I won't consider another spanish provider.
