### ISSUE TITLE
Lack of 4K SDR links

### ISSUE THREAD

**Issue by jorges4lu2** [TheBeastLT/torrentio-scraper#114]
Hi,

Torrentio is not listing some links, especially those 4K SDR.

Let's see an example, Servant S03E02. Torrentio only list 2 4k options, 1 HDR and 1 DV, no SDR options.
If I search on rarbg site there is 1 SDR option (Servant.S03.2160p.ATVP.WEB-DL.DDP5.1.Atmos.x265-MIXED[rartv]), but this is not being listed by Torrentio.

I can see this behavior on some tv shows. Sorry if I persist on this, but I think SDR content is still relevant, specially on some 3rd world countries.

**Comment by TheBeastLT** [comment]
Please stop spamming with duplicate issues
