### ISSUE TITLE
How open source is this?

### ISSUE THREAD

**Issue by ClickyCrispp** [TheBeastLT/torrentio-scraper#115]
The database where you store the links, is that stored just using the caching layer here? 

My point is would I be able to self host this addon for myself? Or is there any additional magic happening outside of this code to populate the db?

Sorry if this is a dumb question, I follow most of the code base, but don't understand that part

**Comment by TheBeastLT** [comment]
Refer ti this issue - https://github.com/TheBeastLT/torrentio-scraper/issues/113#issuecomment-1479151276
