### ISSUE TITLE
load subtitles 

### ISSUE THREAD

**Issue by patrickdrd** [TheBeastLT/torrentio-scraper#117]
hello,
when adding a torrent to a debrid service,
I mean load it manually,
it could contain a subtitle file,
with the same filename,
could you please load this too?

**Comment by TheBeastLT** [comment]
Hi, indexing subtitles from torrents is a big task in itself. But regardless that, most debrid services do not provide direct download links to non video files, so there would be no way to download them through debrid. I think only debrid link can provide download links to non video files.

**Comment by patrickdrd** [comment]
there are links for srt files, e.g.:
https://i.imgur.com/gz0IazY.png

**Comment by patrickdrd** [comment]
I could get you in touch with alldebrid guys (from which is the screenshot above)
so that you could find a solution together,
what do you think @TheBeastLT ?
