### ISSUE TITLE
Feature Request - Scrape Plex Server

### ISSUE THREAD

**Issue by MrMeatballSub** [TheBeastLT/torrentio-scraper#118]
Would it be possible to add this to the providers?  This would be the perfect combination of personal collection with the greatness that already is torrentio.  The only thing that keeps me on seren and umbrella is the ability to scrape my personal plex server.  

Is this something you would consider?  I would be willing to donate or pay for this to be added.

Thanks sir for this already great addon

**Comment by TheBeastLT** [comment]
No, that's not possible by this addon. It's deployed remotely and is only meant for torrent providers. It cannot access anything on your local machine. It has to be new addon that you would deploy yourself on your local network.
