### ISSUE TITLE
Method for getting movies on my hard drive to show up in stremio list

### ISSUE THREAD

**Issue by MrMeatballSub** [TheBeastLT/torrentio-scraper#119]
Hey there, just got a quick question.

Is there a method for getting a movie file located on my hard drive to show up on the source list when selecting a movie?  I'm curious if there is any available method for doing this at this time, maybe by uploading my file to one of the current providers cloud? (put.io, realdebrid, premiumize)

Thanks for reading

**Comment by TheBeastLT** [comment]
@MrMeatballSub this is not a repository to ask questions about stremio, it's in no way related to this addon. Please use appropriate channels for such questions like reddit or discord.
