### ISSUE TITLE
Addon not discovering torrents I know are available on the supported sites

### ISSUE THREAD

**Issue by ignamiranda** [TheBeastLT/torrentio-scraper#120]
When you look up Dimension 20 seasons 1 and 2, torrentio is able to find the correct torrents. But season 3 doesn't come up even though the same uploader shared them on the same site with the same formatting in the torrent name. This is true for other seasons as well.

**Comment by TheBeastLT** [comment]
Hi @ignamiranda , some of the seasons were indexed as a different show. Should be fixed now, thanks for reporting.

**Comment by ignamiranda** [comment]
Awesome! Thanks for the quick fix
