### ISSUE TITLE
Request to add cinecalidad.run

### ISSUE THREAD

**Issue by DallasBelt** [TheBeastLT/torrentio-scraper#121]
#72 gives links in Spanish from Spain (Castellano). There is cinecalidad.run which contains links in Latin American Spanish (Mexico). Could it be possible to add it to Torrentio?

Thank you.

**Comment by TheBeastLT** [comment]
Since a latino specific content was requested by quite a few users I've added the one you've suggested. And also selecting latino language in config.

**Comment by DallasBelt** [comment]
Thanks a lot! :D
