### ISSUE TITLE
Exclude qualities/resolutions and Dolby Vision

### ISSUE THREAD

**Issue by crapapult** [TheBeastLT/torrentio-scraper#123]
Hi.
For some reason when I want to exclude everything except Dolby Vision, torrentio won't show any streams available. Leaving just HDR/HDR10+/DolbyVision has the same behavior. I thought these parameters work both ways. If I uncheck 4K, Dolby Vision, HDR/HDR10+/DolbyVision and exclude everything else, everything works and I get results with DV, 4K etc.
So if I just want to see DV releases in Stremio and nothing else, I can't. Is there a possibility that you can fix this behavior?

**Comment by TheBeastLT** [comment]
That option is about excluding streams based on some tags, not including. Having only DV is not possible atm using that option, as usually tvs support only hdr, or hdr and DV, haven't seen only DV.

**Comment by crapapult** [comment]
> That option is about excluding streams based on some tags, not including.

Correct, but it doesn't exclude everything except DV and so it's not working as expected. I assumed that every option in that list works both ways as if I leave just 4K or 1080, it works and outputs results to stremio.

> usually tvs support only hdr, or hdr and DV, haven't seen only DV

It's not about TV capability it's about filtering torrent files results. Now Torrentio outputs results as **Torrentio 4K**(for sdr), **Torrentio 4K DV**(for dolby vision), **Torrentio 4K HDR|DV**(for hybrid files) or **Torrentio HDR10+|DV** etc., so it already knows and separates different 4K formats. On rarbg(and not only) there's multiple "DV only" releases because it's how it works. Nflx and others, stream files in this way and not hybrid. Not everyone needs all-in-one files if there's smaller one format only, I'm not the one making the rules, it is how it is.
So if your TV is capable of DV you can watch DV only files or hybrid HDR|DV files, it's your choice.
And torrentio is already capable of excluding everything that you don't need except it's not working for some available options.

**Comment by TheBeastLT** [comment]
The HDR/DV exclusion options are working as expected, and I don't see any use case that would be valuable to add from your explanation.
