### ISSUE TITLE
Cinecalidad changed domain

### ISSUE THREAD

**Issue by DallasBelt** [TheBeastLT/torrentio-scraper#124]
Hello dear developer. You kindly added cinecalidad.run provider and it's been working fine (not always with RD). Anyway, I noticed that the new domain is now https://www3.cinecalidad.ms. Does this affect the functionality?

Also, I'm wondering if Torrentio scrapes only .torrent files? Can it work with links for RD supported providers? I ask this because some content don't come in torrent files and I have to use Unchained to cache it.

Thanks a lot for your patience.

**Comment by TheBeastLT** [comment]
Hi, I think this is a different version of this website. Torrentio uses https://c23.cinecalidad.com.mx 
Also this addon is only for torrents.
