### ISSUE TITLE
Replacement Service for RARBG

### ISSUE THREAD

**Issue by papachefcool** [TheBeastLT/torrentio-scraper#126]
Since RARBG shut down, is it possible to include alternate providers in its place?

NQ-RARGB seems to be a somewhat decent replacement for the old site, and is open source.

https://github.com/Not-Quite-RARBG/main

**Comment by TheBeastLT** [comment]
There are already many providers included, which will take it's place.
Also previous entries from rarbg will still be there since they were indexed.

**Comment by hvmzx** [comment]
It would be nice to keep the old one just in case, and add the new one : https://www.reddit.com/r/TheRarBg

They are a fork of the old one and they haven't gone down ever since
