### ISSUE TITLE
What about Bitsearch ?

### ISSUE THREAD

**Issue by daniwalter001** [TheBeastLT/torrentio-scraper#127]
Hi @TheBeastLT , I just some interesting website, [https://bitsearch.to](https://bitsearch.to). I think it might be good if you can manage to add it to the list, since it is very interesting.

**Comment by TheBeastLT** [comment]
This is a DHT  crawler and they are usually not well categorized (some series/movies not included in correct categories, porn is often included in movie/series categories and etc), so I won't be including any DHT crawlers as it would bring just more unfiltered trash.
