### ISSUE TITLE
Stremio torrentio nyaa

### ISSUE THREAD

**Issue by LeonhardtFR** [TheBeastLT/torrentio-scraper#128]
Hello

I noticed that the torrentio addon only fetches torrents with "english translated" subtitles (dropdown list on nyaa site).  As a result, the search is reduced and I cannot find my language (vostfr) in quite a few cases.  On nyaa there may be many more torrents than those displayed due to this filtering limitation.

Is there a way to ask him not to filter? An alternative ? I really need help.

Thank,

**Comment by WaLiD-DK** [comment]
Hi,

Yeah, it would be helpful. Like french torrents they use (VOSTFR) and it doesn't detect it due to filtering limitations.

**Comment by RyuSanPy** [comment]
Yeah, that would be awesome, as a spanish speaker there are very few in my language too.

**Comment by TheBeastLT** [comment]
Similar to #133
