### ISSUE TITLE
Request to add providers

### ISSUE THREAD

**Issue by DallasBelt** [TheBeastLT/torrentio-scraper#132]
Dear developer. I'd like the Latino providers to grow a bit. I found some that could make it to Torrentio, if there's a possibility to add them by you. These are:

- https://alt-torrent.com
- https://yestorrent.org
- https://www.elitetorrent.com
- https://pelisyseries.net

Thanks a lot for your hard work. I'm sorry if my request is too much.

**Comment by TheBeastLT** [comment]
Hi, for some of those it's not even possible to get torrent/magnet link and others don't seem to provide any unique content.
I don't think these are good content providers.
