### ISSUE TITLE
[Request/Suggestion] Add new sorting filter and provider

### ISSUE THREAD

**Issue by WasabiDesuKa** [TheBeastLT/torrentio-scraper#136]
Hello,

First, thank you very much for your work on this add-on. 

I'd like to know if its possible to add a new sorting filter. I'd prefer a recent torrent over an old one to avoid to be "flashed" by the local authority. Or at least if its possible to show the date of the upload.

Also would it be possible to add yggtorrent as a new french provider ? I know its been requested in the past and there's a lot of demand. Its a private french provider which has a lot of content. Since its a private one, it would requiere username and password options.
Sometimes the address can change because of DNS block, the domain can be monitored here : https://yggland.fr/FAQ-Tutos/#status
Ressources : 
From Elementum - 
https://[raw.githubusercontent.com/elgatito/script.elementum.burst/master/burst/providers/providers.json](https://raw.githubusercontent.com/elgatito/script.elementum.burst/master/burst/providers/providers.json)

From JimmyLaurent -
https://github.com/JimmyLaurent/torrent-search-api

Regards,

**Comment by TheBeastLT** [comment]
Hi, as was answered before, private trackers will never be part of torrentio.
