### ISSUE TITLE
Torrentio not scraping episodes of a certain series/season

### ISSUE THREAD

**Issue by priapic-aubergine** [TheBeastLT/torrentio-scraper#137]
Just came across this in reddit at https://www.reddit.com/r/StremioAddons/comments/159io4t/shows_not_showing_up/ and was extremely curious what was happening.

The series "Too Hot to Handle", specifically Season 5, has been on TPB for quite a while (with upload dates from July 14 to July 21).

However, Torrentio doesn't manage to scrape a single link for this season (RD cached or not). It has links for seasons 1-4 though.

Tried it on other apps+scrapers (Wako+Helios, and Kodi+Seren), and these find a couple of links for each released season 5 episode.

Wondering what would cause Torrentio not to scrape these

**Comment by shscs911** [comment]
@TheBeastLT 

Having a similar issue with the show, "Only Murders in the Building".  It's showing only the Season Pack from 1337x and not individual episodes.

Individually searching the torrent sites configured in Torrentio shows many additional uploads for the same show. This s happening with all 3 Seasons of the show.

### Stremio
------------
![Stremio](https://github.com/TheBeastLT/torrentio-scraper/assets/44034402/d36f4283-8d85-4272-a017-1821088b739d)

### 1337x
---------
![1337x](https://github.com/TheBeastLT/torrentio-scraper/assets/44034402/e9e0c9be-519f-42a5-9658-ce659227267f)

### TorrentGalaxy
---------------------
![TorrentGalaxy](https://github.com/TheBeastLT/torrentio-scraper/assets/44034402/bb5f6f95-d7d0-49ac-9450-e78846200984)

### Torrentio Config
-------------------------
![Torrentio-config](https://github.com/TheBeastLT/torrentio-scraper/assets/44034402/f45218d6-78c8-451e-9bf0-d34584b8c3b9)

**Comment by TheBeastLT** [comment]
@shscs911 In your case imdb migrated this show to a different if (from `tt12851524` to `tt11691774`) so some indexed files were no longer matched with the new id.
Both of these series should contain streams now.

**Comment by shscs911** [comment]
Thank you so much for fixing that.
