### ISSUE TITLE
Stremio torrentio provider adding request 

### ISSUE THREAD

**Issue by KARANRSB** [TheBeastLT/torrentio-scraper#138]
Hi guys I've been using torrentio+Rd for all my hollywood content and have no issues but for Indian movies and shows including Tamil,Telugu,kannada etc it's only available on tamilblasters, Tamilmv etc.Now I know there is already a tamilblasters addon which provides links but it doesn't support real debrid and requires us to manually go to the website copy magnet link and paste it into real debrid in order for me to view it buffer free same as torrentio instead of automatically doing for me I do it manually so I just wanted to request the creater of torrentio to add tamilblasters to it so that This can be avoided.It would be of great help for Indian fans and users of stremio.
Please hoping that u consider my request.

**Comment by TheBeastLT** [comment]
Duplicate #74

**Comment by jrjaggari** [comment]
Hello, a small request to add https://tamilblasters.lat/ as provider. They have a large and very updates database of Indian and English Content.
Someone has already made a scraper ( addon linked attached below)
https://github.com/mhdzumair/tamilblasters_streamio_addon
But would love to download via RD
