### ISSUE TITLE
Request to fap.iss.one Provide (NSFW)

### ISSUE THREAD

**Issue by ni3x** [TheBeastLT/torrentio-scraper#139]
Url: https://fap.iss.one/

There are no provider for NSFW Anime and Hentai. Adding this provider will help to fetch links.
It's is similar to nyaa.si

**Comment by TheBeastLT** [comment]
First I don't want torrentio to provide NSFW content, and second there's no metadata provider for hentai in stremio (kitsu addon does not provide it)
