### ISSUE TITLE
Not returning RD links

### ISSUE THREAD

**Issue by dayloon** [TheBeastLT/torrentio-scraper#14]
Hi, 
I've got an issue with torrentio and real debrid.  It was all working fine but now it's not returning any RD links at all.  I've uninstalled / reinstalled,  checked my RD account but nothing is working. 
 
Other apps & addons are working,  just not the torrentio addon

**Comment by TheBeastLT** [comment]
Hey, it's working on my side. Checking the logs it seems there was temporary problem with RD (timeouts).

**Comment by dayloon** [comment]
Yeah it's working now.  Weird.  Thank you for the swift response

**Comment by gonzalo-hvega** [comment]
Is there anyway to force the addon to re-scrape? For some reason the movie I tried to watch this morning still shows no links. It appears the addon is not trying to search for that one again, other movies I try find plenty of links... searching for Mulan 2020 using windows app

**Comment by TheBeastLT** [comment]
@gonzalo-hvega Responses from addons are cached on device for configured time by the addon. For Torrentio it's 4hrs. Not sure if there's a way to reset the cached responses. You could open a link on one device, then it will be added to `Continue Watching` list and then it should be synced to other device and you should be able to start it on another device.
