### ISSUE TITLE
The Torrent9 used is not the official

### ISSUE THREAD

**Issue by razeNFR** [TheBeastLT/torrentio-scraper#143]
I searched on official Torrent9, https://www.torrent9.gs/ when I noticed that on Stremio some film or series was not available while on official Torrent9 they are.

Would it be possible to modify this in the source so that I can create a custom version for myself or is it possible to modify this directly in Torrentio?

I think you use torrent9.to but the real one is actually torrent9.gs

**Comment by TheBeastLT** [comment]
It is not possible, scrapers are separate from the addon. Please don't spam with such issues without any proof.

**Comment by razeNFR** [comment]
But for exemple when i search for the Simpson s34 is in vostfr only, but on the torrent9.to or torrent9.gs they have the s34 in french so, why in stremio with torrentio i didnt see them ? Yet I configured torrentio correctly, so I don't understand...
