### ISSUE TITLE
How to run torrentio addon locally? + yggtorrent tracker 

### ISSUE THREAD

**Issue by IoALFANO** [TheBeastLT/torrentio-scraper#144]
Hello,

I'd like to run the torrentio addon locally to add my own yggtorrent tracker (I use alldebrid).
In the addon folder :
- I updated DB URI in lib/repository.js (I created a postgres DB)
- I added my tracker in lib/magnetHelper.js
- I execute the index.js file

I know I need to adapt the code but I'm lost.
I'd appreciate any help.

Thank you.

**Comment by TheBeastLT** [comment]
Please use search and see past issues https://github.com/TheBeastLT/torrentio-scraper/issues/113#issuecomment-1479151276
