### ISSUE TITLE
[Request] A "Simple" design option to the media listing

### ISSUE THREAD

**Issue by a000744210** [TheBeastLT/torrentio-scraper#146]
Currently the media listing is full of technical information. Every time I have set this addon up for someone, they are confused with the terminology. I propose a config option to https://github.com/TheBeastLT/torrentio-scraper/blob/a40cb9381213cac568ebdd154e62289c9f8a0c01/addon/lib/streamInfo.js#L11C15-L11C15 which can remove the terminology such as torrent file name, seeders, provider, for the non tech savvy users whom use this addon. This should make the addon more user friendly. This config option would be decided in the install page along with all the other config options. 

Before:
![image](https://github.com/TheBeastLT/torrentio-scraper/assets/29644944/8db1830f-33d7-4ac0-9c17-763377e9a3b6)

Mockup:
![image](https://github.com/TheBeastLT/torrentio-scraper/assets/29644944/32c68bc1-ee0e-4a6d-a4a7-5b17f87ad100)

**Comment by TheBeastLT** [comment]
Sorry this is not netflix, and the information provided is important. It would be hard to decide what is medium and etc. Which would just raise more questions.
