### ISSUE TITLE
Variety

### ISSUE THREAD

**Issue by hotfuzz10** [TheBeastLT/torrentio-scraper#150]
Noticed a4k/coco scrapers manage to find cached files certain old tv programs and old movies where torrentio doesn't. e.g. (mythbusters, survivorman, few 50s movies etc) not sure if able to use some of their providers for scraping would be great.

Apart from that torrentio is brilliant and thank you to creator and community that helped.

**Comment by TheBeastLT** [comment]
Seems like there're quite a few links returned by torrentio for the shows listed. Since this addon 8s meant for stremio and not for kodi, maybe the developers of those scrappers are using some config of the addon that doesn't return everything.
