### ISSUE TITLE
Possible to add more french trackers ?

### ISSUE THREAD

**Issue by razeNFR** [TheBeastLT/torrentio-scraper#152]
Hello,

I would know if its possible to add more french tracker (list : ww1.torrent9.cz , cpasbien.eu , voirfilms.media , vostfrserie.co , oxtorrent.co) because Torrent9 miss much series/movies.

I know its lot of work for you, but just wanna know if its possible or not..

Thank you :)

**Comment by TheBeastLT** [comment]
Atm I'm not planning on adding more fr providers, torrent9 seems enough.
