### ISSUE TITLE
Request - Exclude Sound Formats (TrueHD, DTS-HD, etc)

### ISSUE THREAD

**Issue by tundrablasen** [TheBeastLT/torrentio-scraper#153]
We have already and "Exclude" tab in torrentio which is super helpful
![grafik](https://github.com/TheBeastLT/torrentio-scraper/assets/46343142/7740aee2-cbd2-4b2e-86aa-43c2fbf8acac)

it would be great if we could prolong this list of formats which can be excluded. currently its only focused on **Video** formats.

Please add to the list **Audio** formats. For Example:

- TrueHD
- DTS
- DTS-HD
- OPUS
- ATMOS
- FLAC
- etc.

Reason for that:
Many Video Players (like the internal android TV Player used within Stremio, is not capable of using certain Audio formats (for Example "TrueHD"). Therefore playback is failing or a fallback player gets choosen with has other disadvantages.

Kodi Addons like "fen" or "umbrella" have already included such a filtering option. there we could get a comprehensive List of audio formats which should be excluded. i can also provide a list if necessary.

Thank you for considering this

Edit:
Just to specify: I just want the list of the current exclude logic prolonged with additional entries. I do not want to change the sorting logic. So no additional confusion will be added to the end user. You can just exclude more options (audio formats)

**Comment by tundrablasen** [comment]
![IMG_0600](https://github.com/TheBeastLT/torrentio-scraper/assets/46343142/459ee4d8-fbcf-426c-b335-d80e08968d01)
![IMG_0601](https://github.com/TheBeastLT/torrentio-scraper/assets/46343142/9540f43e-ffb9-4d7f-9a7d-d48cd0e0f352)

**Comment by TheBeastLT** [comment]
Atm I'm not planning adding audio formats to this list, as they are not always available in the torrent title and most players Stremio use can fallback to software decoding for some of these formats, so I don't see it as a huge issue.

**Comment by tundrablasen** [comment]
You are definitely in the right to not look at this issue, but i just wanted to say that i do not see your logic in your argumentation.

1. your video formats are also not always in the torrent title. you still make it available to filter it out, in case they are (e.g. "Remux")
2. even high quality media player (like my nvidia shield tv) have issues with certain sound formats (TrueHD). Exoplayer does not play it, and fallback (libVLC) does play it but without sound. If we then look just to the broadness of other low quality media player with bad codec support.... lets not talk about widely popular amazon fire tvs.

i just thought this is a quick win, since you just needed to copy paste code and add multiple different strings.

But thanks anyway for torrentio. its awesome.

**Comment by TheBeastLT** [comment]
I have nvidia shield and TrueHD videos play fine, although I don't have a soundbar so they are downmixed. I'd suggest to check you tv settings, and also maybe try playing with tunnelled playback setting in stremio.

**Comment by billw1** [comment]
Please reconsider doing this. on Samsung TVs, DTS won't play at all and there's no fallback or anything. Basically every torrent with DTS audio is labelled with it too. It's extremely common with 1080p blurays
