### ISSUE TITLE
Criteria for new site additions? 

### ISSUE THREAD

**Issue by snvoid** [TheBeastLT/torrentio-scraper#155]
Hi, i was wondering if there was some criteria you used for new site additions (to be supported)? I read old threads where you mentioned DHT crawlers as not something you were looking to support at this time. How can one determine if a site is a DHT crawler. 

Is there a process for putting forth suggestions for new sites to be added?  Thanks

**Comment by TheBeastLT** [comment]
It would need to offer quite a bit of unique content that's not found in other providers. Also I'm not looking into adding too many language specific providers.
Adding a new provider is not an easy task, as you also need to index all the items from the past that it provides, and that takes quite a bit of time and effort.
