### ISSUE TITLE
Request - put the "multi audio" at the top

### ISSUE THREAD

**Issue by razeNFR** [TheBeastLT/torrentio-scraper#156]
Its possible to put torrent marked as "multi audio" at the top of the torrents list ? Because sometimes i have to scroll down to search a multi audio file to have my language in. I think its smarter to put them at the top of the list.

**Comment by TheBeastLT** [comment]
Audio is not known in these cases, so putting it at top (not sure on what conditions even, probably you have in mind when priority foreign language is configured) would make it useless for many people as in many cases it might not contain the language that the user needs.
