### ISSUE TITLE
[bug] Using Real Debrid results in `Player Error`

### ISSUE THREAD

**Issue by emlautarom1** [TheBeastLT/torrentio-scraper#157]
When setting up Torrentio (https://torrentio.strem.fun/configure) with Real Debrid I get constant `Player Error` when trying to play any media. Results are shown and available on Stremio, but I cannot play any content. If I disable Real Debrid and use torrents directly then it works normally.

- Real Debrid works fine outside Torrentio (tested using their website and using other third-party apps that rely on their API). I also refreshed the token with no luck.
- Stremio was tested on Android TV and on plain Android 13.

**Comment by TheBeastLT** [comment]
What error are you getting exactly. This addon does not manage the the videos, so it's not responsible of the device is not able to play them.

**Comment by emlautarom1** [comment]
![Screenshot_20231011-152729](https://github.com/TheBeastLT/torrentio-scraper/assets/31224949/14576e5f-264e-47f3-8080-17f60f3b20ab)

Error from Android 13 device running Stremio 1.6.7. If I pick the same link without having RD enabled in Torrentio then I can stream the content no problems.

**Comment by TheBeastLT** [comment]
This is something specific to your device/network and not related to the addon. Try another device and/or use another network/mobile data to test.
