### ISSUE TITLE
Clipboard access makes most users suspicious 

### ISSUE THREAD

**Issue by pantos27** [TheBeastLT/torrentio-scraper#159]
When the average user browse to https://torrentio.strem.fun/ he gets  a permission request to access his clipboard because of this line:
https://github.com/TheBeastLT/torrentio-scraper/blob/12286cba027899c98064698d09ae442cc2f7561f/addon/lib/landingTemplate.js#L477

This makes most users suspicious of the add-on for obvious reasons, even though the intent was naive
https://bufferzonesecurity.com/clipboard-hijacking-attacks-and-how-to-prevent-them/

I suggest wrapping this action behind a button that will write the link to the clipboard instead of accessing it straight away

**Comment by TheBeastLT** [comment]
That is true, tho I don't see it as a big issue atm. I'll try to look into when I have time or I'll welcome a quality PR to improve this.
