### ISSUE TITLE
RealDebrid configured Torrentio stops working at certain times.

### ISSUE THREAD

**Issue by hetp4401** [TheBeastLT/torrentio-scraper#16]
when it stops working (RD torrentio links are stuck on load when you click on them):
- torrentio takes a little longer to load the links
- on the real-debrid site, torrents arent fetched
- stops working from around 12pm to around 11pm I think for me (EDT)

This has been happening for 3 days in a row. If you can check it out that'd be great. 

Thanks!

**Comment by TheBeastLT** [comment]
Hey, there were some issues with the proxies I'm using. Should be back to normal.
