### ISSUE TITLE
[Feature Request] Access Debrid Library

### ISSUE THREAD

**Issue by onlytanmoy** [TheBeastLT/torrentio-scraper#160]
Please provide option to access my Debrid (RD/PM/AD) library from within the Stremio app. This will allow me to play the files that are downloaded in my Debrid My Files.

**Comment by TheBeastLT** [comment]
It is available in Stremio via Discover screen, there you select `Other` and then your debrid catalog. Just check that you haven't disabled the catalog when configuring the addon as there is an option to disable it under `Debrid options` drop down.

**Comment by onlytanmoy** [comment]
@TheBeastLT thanks for the navigation mate, I now know how to access my Debrid Library from Stremio :)
One observation though: it is displaying only folders (and files within those) at the moment and can play those however it cannot display if I have a video file in my library, the below screenshot will help explain

![image](https://github.com/TheBeastLT/torrentio-scraper/assets/48493659/4d0818f9-d294-4a3f-9215-ee059ed99924)

**Comment by TheBeastLT** [comment]
For PM the catalog is made from `My Files` section in PM, there you can organize however you want, but AFAIK PM creates a folder for each transfer you have, unless you've manually deleted it.

**Comment by onlytanmoy** [comment]
Thanks for the pointer mate. I manually created a folder under My Files section and moved the video files inside that. That way it is now visible in Stremio along with the other folders :) Have a nice weekend.
