### ISSUE TITLE
[Request] Add https://wolfmax4k.com/ as a provider

### ISSUE THREAD

**Issue by kevinfb92** [TheBeastLT/torrentio-scraper#161]
Right now the streams with spanish audio found by torrentio are very lacking, with only 720p releases in a lot of cases.

I think the reason is that the spanish providers that stremio already scrapes from, like mejortorrent, don't add the 4K releases found in https://wolfmax4k.com/ (which afaik is the only source in Spain releasing in 4K right now), and in many cases they won't even add the 1080p versions, which makes watching content with spanish audio in stremio a not so good experience.

I kind of solve this by adding the wolfmax4k torrents to real debrid myself, but this has two drawbacks:
a) Not every user has a debrid
b) Since torrentio doesn't scrape from that source, the stream is not recognized as part of its own series in stremio, so it doesn't show up in the stream list for that series. I still can watch it from the debrid section in Discover, but it breaks the nice user experience from stremio.

If torrentio found torrents from that provider, suddenly every user would get 1080p with spanish audio versions in the stream list for almost every release, and finally get some 4k ones too. I think it would make a big impact.

There's no stremio addon for scraping from wolfmax4k right now, but I always find their magnets on search engines like solidtorrents (I don't know if that would make the implementation easier). Or maybe something easier can be done for getting all the torrents from there, i don't really know how torrentio works under the hood.

**Comment by TheBeastLT** [comment]
Hi @kevinfb92 even if I would be considering adding new language specific provider (which atm I'm not), this website is way to convoluted to scrape, to the point where it's not worth the time investment. You're welcome to make your own version scrapping this site and make a spanish specific addon.
