### ISSUE TITLE
Add ilcorsaronero

### ISSUE THREAD

**Issue by Heisenberge89** [TheBeastLT/torrentio-scraper#165]
Please could you add to the sites also https://ilcorsaronero.link ?thanks

**Comment by Pietro395** [comment]
It is an important provider of Italian material, it would be interesting to add it

**Comment by guglielmobartelloni** [comment]
Second this

**Comment by Pietro395** [comment]
@TheBeastLT Is scraping done on the backend side? How is it possible to contribute by adding a source?

**Comment by danilanx** [comment]
Please add the Ilcorsaronero many contents are not available in Italian and this is the best provider in italy
