### ISSUE TITLE
Request to add sorting by embedded subtitles

### ISSUE THREAD

**Issue by boomoliver** [TheBeastLT/torrentio-scraper#167]
It would be great to have an option to choose only streams that have embedded subtitles for the language you choose. Since the opensubtitles addon is unreliable sometimes i always want streams with embedded subs. It would make it alot easier for my family since its confusing for them when a stream doesnt have embedded subs, and they have to meddle with different subtitles and delay and everything using the addon.

**Comment by TheBeastLT** [comment]
This information is not known from torrent name or description, so it's no feasible do do that. You'd need to open each torrent file with media info tool to know that for sure, and that is just not something you can do easily and requires a lot of resources as there are millions of files indexed.
