### ISSUE TITLE
Torrentio + Debrid Unreliability

### ISSUE THREAD

**Issue by maureenferreira** [TheBeastLT/torrentio-scraper#168]
In my opinion, one of the biggest issues (if not the biggest) for Torrentio + Debrid users currently is the fact that Torrentio quite often fetches torrents which are no longer cached on a Debrid service due to a copyright strike. This issue is only further exacerbated when you have "By seeders" or "By quality then seeders" enabled in the sorting options, as the highest-seeded torrents for any given piece of content are the most likely to be the oldest and most popular ones and therefore have had the highest possibility to have been taken down on a Debrid service already.

This issue can be remedied in a lot of cases by just increasing the max results for torrents in Torrentio to 4 or higher, as this allows for a much higher possibility that one of the torrents Torrentio fetches is cached on the user's chosen Debrid service, but this method is still not 100% reliable and is also very messy and cumbersome, especially if the user has "Show P2P torrent links for uncached" enabled as for every one of the torrents Torrentio loads that isn't cached on the Debrid service Stremio will also display torrent links, which is useless if one of the torrents *does* end up being cached on the Debrid service in the end.

I could go on for a few more paragraphs about the the issues which are spurred from this, but I think I've made my point abundantly clear at this point. In terms of how to go about remedying this situation, I can think of many possible solutions which may or may not work and, as such, have decided to let the developer(s) of this plugin decide for themselves what the best course of action. As always, I'm open to any productive discourse regarding this issue.

**Comment by TheBeastLT** [comment]
Please take it up with RD, as it's an issue on their side. If file is infringing, there api will still return that it is cached, and you'll get an error only when trying to unrestricted the link.
