### ISSUE TITLE
Video size limit in Mbps

### ISSUE THREAD

**Issue by boomoliver** [TheBeastLT/torrentio-scraper#169]
The max size limit is flawed because movies and episodes have different length. I could put the max size as 4GB for 2 hour movies and that would work fine for those, but 3 hour movies will have significantly lower quality because 4GB for 3 hours of content is much less than 4GB for 2 hours of content. Some episodes have 20m runtime, and will look great with around 1GB file size. But 60m and up will look terrible with only 1GB file size. I cant just put it as like 5GB for everything either, because 5GB for 20 minute episodes is WAY too much and my computer cant handle that. If the video size limit is to make so you never end up with videos that your system cant handle, it should be measured in Mbps instead because that's way more consistent. Unless im wrong you can just measure the Mbps by comparing the file size to the video length and then sort based on that. Maybe with an option to choose between the two, although i would always choose Mbps over video file size. Would also be really nice to be able to set a minimum Mbps/file size as well as the maximum one, to make sure you always get good enough quality files, as well as making sure the file sizes arent too big for your system to handle. Love the addon so much though! Game changer

**Comment by TheBeastLT** [comment]
Sadly it's not possible as video length is not known without opening the file, so video file size filter is good enough. You can have different value for movies and series separated by comma.

**Comment by boomoliver** [comment]
Couldn't you scrap that data from Cinemeta or another database like TMDB or IMDB somehow? I mean it already shows what the length of a movie/show is in stremio. Maybe some files could be longer or shorter based on extra scenes or credits but it shouldnt be that significant
