### ISSUE TITLE
Scraping code

### ISSUE THREAD

**Issue by daniel-lxs** [TheBeastLT/torrentio-scraper#170]
Hi, sorry to open an issue to ask a question but do you plan on uploading the scraping part of torrentio? the part that actually populates the DB? I would like to fork and maybe add some new scrapers as I'm needing more latino content. Thank you

**Comment by TheBeastLT** [comment]
Refer to this comment - https://github.com/TheBeastLT/torrentio-scraper/issues/113#issuecomment-1479151276
