### ISSUE TITLE
improve filtering system

### ISSUE THREAD

**Issue by marco-calautti** [TheBeastLT/torrentio-scraper#171]
Currently, the filter system is very basic and does not allow to filter with more complex conditions. For example, say I want to filter out streams which are BOTH HDR and DV, but I still want to keep HDR only, or DV only streams. This is currently not possible.

It would be nice to have a very simple "language" with boolean operators to specify complex conditions like: !(HDR & DV).

This would be very helpful to fix also problems with devices that cannot reproduce some streams (e.g. the Fire TV 4k Max has a bug preventing playing streams with HDR+DV)

**Comment by TheBeastLT** [comment]
That is way to complex and prone to errors and not something I'd like to maintain for little value. Most player can fallback to hdr if tv doesn't support DV when both are available.
