### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by maureenferreira** [TheBeastLT/torrentio-scraper#173]
Currently, while streaming from a Debrid source, Torrentio doesn't fully cache the torrent being streamed. While I understand the reasoning for this, I feel as though there should be an option in the Torrentio configuration to enable full caching of torrents being streamed from a Debrid source. There's a few reasons I think this functionality would be very useful, one of which being that for people with spotty internet connections or who are using spotty mobile data this would allow them to enjoy a much smoother viewing experience as whenever their connection cuts out there's still more of the file cached so they can still enjoy their content even if their connection is out for a minute or two. I suggest adding an option in the Torrentio config to cache torrents from Debrid sources entirely and maybe also an option to cache them entirely, maybe a text box where users can enter the percentage of a torrent they'd like to be cached (e.g. 25%); Of course, figuring out how to handle only caching a percentage of a torrent would be a little trickier as, for example, you'd probably want to make it so 25% of the portion of the torrent ahead of the user is cached at all times and not just the first 25%, whether or not to delete the portions that have already been watched, and so on. As always, I'm open to any productive discourse regarding this issue.

**Comment by TheBeastLT** [comment]
Stremio addons just provide information how to access a certain stream. They cannot influence how it's played or anything related to the player, that's up to the player used in stremio application.
