### ISSUE TITLE
Feature request : Ability to Prioritize Dolby Vision and HDR (With capability to prioritize Dolby Vision over HDR)

### ISSUE THREAD

**Issue by Vudupulz** [TheBeastLT/torrentio-scraper#175]
This is available in a few Kodi add-ons and I find them incredibly useful. 
Requirements : 
Prioritize Dolby Vision -> Show biggest file 
Prioritize HDR -> Show biggest file
Rest
Thank you for all your hard work!

**Comment by TheBeastLT** [comment]
Hi, HDR/DV modifiers are already quite visible next to the quality so it shouldn't be hard to distinguish them. I'm not planning on adding such a feature.
