### ISSUE TITLE
Offcloud links not working

### ISSUE THREAD

**Issue by ragmehos** [TheBeastLT/torrentio-scraper#179]
I have setup offcloud as the debrid provider with stremio and torrentio, and any cached links do not work, it fails with unexpected error try again later but with no luck as retries even after many days are still failing.

If I get the link from offcloud, it plays fine. Clicking on the content from the debrid catalog also fails, with torrentio failing with "500 Internal Server Error"

Can you please take a look to see if offcloud debrid setup is working fine or what's going wrong? Thank you.

**Comment by ragmehos** [comment]
@TheBeastLT if you can take a look when you get a chance, thanks.

**Comment by TheBeastLT** [comment]
Just tried and all is working fine for me, check if you have a valid subscription.

**Comment by ragmehos** [comment]
> Just tried and all is working fine for me, check if you have a valid subscription. Edit: I think I just found one issue where it would fail to get the download link for torrents that have video files in nested dirs. Such cases should work now.

Awesome, thanks, will try it out. The one that was particularly failing for example was The Simpsons S35E08 - not everything failed, but some of them failed. I will test it out to see if this was the issue and its fixed. Thanks again

**Comment by ragmehos** [comment]
I just tried, but fails again, can you for example try playing The Simpsons S35E08 - there is one link cached on OC but it fails with an error. The URL is linked [here](https://github.com/TheBeastLT/torrentio-scraper/issues/179#issuecomment-1857242844) - one is from the episode and the other from the debrid catalog - both fail for me.

**Comment by TheBeastLT** [comment]
Sadly I've used up my free links and can no longer test, but I see that offcloud api fails with some error `Bad archive` when trying to add a magnet link

**Comment by ragmehos** [comment]
I can send you my API key if you want to test, let me know how to send it, this one just seems to be its own file - I have seen this to happen with quite a few files, but some of them also play fine, which is super confusing. I can play this file fine directly on VLC when I copy the link from OC though.

**Comment by TheBeastLT** [comment]
You can send me via discord PM to `thebeastlt`

**Comment by ragmehos** [comment]
Spoke to BeastLT over discord and it seems to be an issue with OC and not much we can do here, thanks TheBeastLT.
