### ISSUE TITLE
Add an option to prioritize 4K Dolby Vision Files to the "exclude list"

### ISSUE THREAD

**Issue by JustaDumbass** [TheBeastLT/torrentio-scraper#180]
Hi!
Just to state the obvious: I love your work and want to thank you so much for the entire stremio community!

But I noticed and issue with torrentio recently: It is almost impossible to get 4K Dolby Vision files as a priority. I have tried to exclude Bluray Remuxes (which presumably include 4k BD as well), tried to exclude HDR/HDR10+/Dolby Vision and nothing seem to work. Very often some 1080p rips with bigger size are ranked ahead of DV (which is often not even discernable if the file name is too long).

If I disable 1080p I get no hits when I search for movies/TV shows that don't have 4k releases. If I disable 4K there are no 4K releases left. Do you get the Catch22 I try to describe?

I think adding an option to prioritize 4K Dolby Vision versions is the best fix for this solution (or does anybody have a different solution?)

**Comment by TheBeastLT** [comment]
Sort by quality then size, if you don't want to mix 4k with 1080p... 
Exclude qualities is an option to exclude stream on sort or prioritize them. Atm I don't see a need for such a feature
