### ISSUE TITLE
Add option to exclude 3D releases

### ISSUE THREAD

**Issue by the9655a** [TheBeastLT/torrentio-scraper#182]
I occasionally run into 3D releases and would like the option to hide them from the list of sources. I don't have anything to watch them with either.

**Comment by skbtwiz** [comment]
I would like to add that for those of us who actually have 3d stuff, it would also be nice to have an option to hide all BUT the 3D links. It is extremely frustrating to have to read through each link's description to find "SBS" or "3DSBS"  or other formats.
