### ISSUE TITLE
Premiumize links don't appear to be correct

### ISSUE THREAD

**Issue by HassanWasHere** [TheBeastLT/torrentio-scraper#183]
Some links appear to be either the wrong quality or the premiumize transcoded version (i'm not exactly sure what's going on), this only seems to happen for some links on some shows. I click on 1080p remux and then open with VLC to check the codec information which which shows its a 720p stream however opening this exact same source using RD appears to work as intended.

**Comment by TheBeastLT** [comment]
Are you watching from stremio Web platform?

**Comment by HassanWasHere** [comment]
I can replicate it from both the Windows application as well as Stremio Web

**Comment by TheBeastLT** [comment]
When playing in web (detected based on user agent), for premiumize it returns a stream link that is supported by most browser and not the actual full file download url as those are usually not supported in browsers. This shouldn't occur on desktop app, tho.
