### ISSUE TITLE
Add TorBox.app as provider

### ISSUE THREAD

**Issue by Wamy-Dev** [TheBeastLT/torrentio-scraper#184]
Would be good to add TorBox.app as a provider. Has a free plan and has a full and complete API.

**Comment by Jamescsthowards** [comment]
Torbox support would be amazing

**Comment by ragmehos** [comment]
+1 to the above comments, torbox support would be good. Just added it for another addon, but I am not familiar with nodejs, otherwise would be happy to help.

https://github.com/mhdzumair/MediaFusion/pull/72

**Comment by nreis96** [comment]
@TheBeastLT any chance we could see torbox added soon? If so, when? I very much prefer it to other providers. Thanks a lot for your hard work!

**Comment by Sanket9225** [comment]
@TheBeastLT  Please consider adding support to TorBox.
It allows sharing account with your friends and family members.

**Comment by shayisnear** [comment]
would be amazing to add

**Comment by Rrhul0** [comment]
Hi @TheBeastLT , I saw this issue and thought adding support of Torbox debrid could be really helpful. I’ve actually got a working version of the feature, though it’s not fully complete yet. I’d love to contribute this if you’re open to outside contributions!

**Comment by fumg** [comment]
Adding to the list of people who would appreciate that torbox.app is supported

**Comment by Cueball666uk** [comment]
An official addition of Torbox to Torrentio would be awesome !

**Comment by usc1787** [comment]
please add official support. Thank you.

**Comment by Pentonize** [comment]
+1 for torbox especially with Real-Debrids latest announcement: https://x.com/RealDebrid/status/1859673163681960169?t=d13BGEonsE4DDP3Yr9QzFw&s=19

**Comment by NineKain** [comment]
+1, RD is dead

**Comment by Rrhul0** [comment]
Checkout this reddit post https://www.reddit.com/r/StremioAddons/s/nPvcBBF1CJ 
We can use the unofficial Torrentio with Torbox support, untill devs add the official support for it.

**Comment by Javier10103** [comment]
Please add this since RD is dead

**Comment by Rikj000** [comment]
Hi @Rrhul0,   
could you please consider opening a PR of: https://github.com/Rrhul0/torrentio-scraper/tree/ft-torbox   
And linking it to this issue?

I've noticed inactivity on the branch for a few weeks now,   
and that the fork appears to work as intended.

I'm sure @TheBeastLT would appreciate it,   
if he doesn't, then he can just close the PR, and then you have your answer.

It would get things moving at least, which is crucial now I think,   
due to Real-Debrid being handicapped,    
and most other Debrid providers residing in the EU where similar things can happen to them.

**Comment by kaumac** [comment]
Also looking forward to this now that RD is gone.
I'm relying on media fusion and comet for now but Stremio is so much better

**Comment by Pietro395** [comment]
+1 for TorBox!

**Comment by Blockr22** [comment]
+1 Torbox

**Comment by D4rkm3ch** [comment]
+1 Torbox

**Comment by onfire-d** [comment]
+1 for Torbox, specially since all this RD/AD situationship
