### ISSUE TITLE
How is a magnet retrieved from an infohash?

### ISSUE THREAD

**Issue by vezaynk** [TheBeastLT/torrentio-scraper#185]
I'm exploring the torrentio source and it seems like it returns an "infohash" if realdebrid isn't configured.

I'm assuming that it later looks up the magnet url based on that infohash on the stremio server. Where I'm struggling through, is how does that happen?

I can't find an endpoint that converts infohashes to magnet links (despite there being an internal function to do that).

**Comment by TheBeastLT** [comment]
This is not related to the addon.

**Comment by vezaynk** [comment]
Its a question about how the add-on works. Its not unrelated.

**Comment by TheBeastLT** [comment]
This is a repo for a specific addon's issues. For general info about addons look https://github.com/Stremio/stremio-addon-sdk
