### ISSUE TITLE
Items in Debrid Catalog are not sorted properly

### ISSUE THREAD

**Issue by AlyafeiAli** [TheBeastLT/torrentio-scraper#187]
Hi, TheBeastLT  
I hope you're doing well

I downloaded [this torrent](https://nyaa.si/view/1419013) to my Real Debrid cloud, and I've noticed that the episodes under Debrid Catalog tab are not sorted alphabetically as shown in the screenshot below.  
Moreover, the sorting in Android is different than the sorting in AndroidTV. In Android, the first episode is episode 012, while in AndroidTV it's episode 008.  
This is not a big issue generally, but it is quite problematic with shows with many episodes like the one I've linked.

I really appreciate your work, thank you!

![image](https://github.com/TheBeastLT/torrentio-scraper/assets/52626961/03db9cc5-9f1f-4dfe-8618-30cc25d8b285)

**Comment by TheBeastLT** [comment]
Sorting on torrent not indexed by torrentio is based on order of the torrent itself by the person who created it. No plans to change it atm.
