### ISSUE TITLE
Add bitsearch to torrerntio

### ISSUE THREAD

**Issue by ericvlog** [TheBeastLT/torrentio-scraper#188]
website request : https://bitsearch.to/

Hello just use torrentio with Real-debrid, when searching the movie " i saw the devil" (2010) on stremio using rd, the max filesize i get from result is 1080p 12.98Gb max file size. real-debrid cache

But using kodi addon fen with cocoscraper it search throught bitsearch and find same movies with 1080p 30 ~ 40Gb also real-debrid cache torrent.

and throught bitsearch it can find more rare movie or tvshow resource.

Thank for your consider.

**Comment by TheBeastLT** [comment]
Please use search before opening new issues.
