### ISSUE TITLE
What writes to the database?

### ISSUE THREAD

**Issue by cmspam** [TheBeastLT/torrentio-scraper#189]
I've tried to set it up in a local docker, so that I can develop on it and maybe make some additions/modifications.

Forgive me for any stupidity, but I always get:
Failed request tt0099785: SequelizeDatabaseError: SQLITE_ERROR: no such table: files

I can't seem to find what initializes/populates this database.

Again, sorry for any stupidity.

**Comment by theblazehen** [comment]
Not sure where it's created, but tables seem to be defined in https://github.com/TheBeastLT/torrentio-scraper/blob/master/addon/lib/repository.js
