### ISSUE TITLE
The indexing of results in Spanish from nyaa.si does not return results

### ISSUE THREAD

**Issue by TitanPhoenix7** [TheBeastLT/torrentio-scraper#191]
Hello, I am trying to watch anime through torrentio.

I use nyaa.si and when I search for results on the web with subtitles in my language (Spanish), they do not appear on torrentio but they do appear on nyaa.si website.

I don't know if it's because maybe torrentio need to be indexed properly with the tag ES/ESP/LAT or español/Español/latino to detect these results which are with that tag in nyaa.si 

I would love to be able to continue using torrentio to watch anime instead of having to download or manually search for it on nyaa.si.

Thank you!

**Comment by TheBeastLT** [comment]
Duplicate #133
