### ISSUE TITLE
Feature Request - Proxy Settings for Stream Links

### ISSUE THREAD

**Issue by devenderkg** [TheBeastLT/torrentio-scraper#194]
I am writing to submit a feature request that I believe would significantly enhance the functionality of your streaming service. The addition of a proxy setting for stream links would provide users with greater control over their online privacy and security.

The proposed feature involves the implementation of proxy settings for stream links within the application. This functionality would allow users to route their streaming traffic through a designated proxy server, providing increased anonymity and security during their online streaming activities.

**Comment by TheBeastLT** [comment]
That's a very niche use case and would mess with caching. You can always write your own addon and proxy through it for such use cases.
