### ISSUE TITLE
Playback issues with multi-part movies (MPEG2-TS)

### ISSUE THREAD

**Issue by LavaTile** [TheBeastLT/torrentio-scraper#198]
Hi, I've noticed that certain movies, specifically those that are split into .ts segments, don't play as expected. They will start playing at a seemingly random segment, which is apparently caused by Torrentio redirecting to a RD link ending in `00071.m2ts` (this is a segment part-way through the movie)

I've observed this with a torrent identified by infohash `2a2a6cbc7cc948053f156b7dd807d9b44cfad3fa`  (92.55 GB)

**Comment by TheBeastLT** [comment]
Stremio can only play one file at a time, so if m2ts is not in one file than nothing can be done, choose a different source.

**Comment by LavaTile** [comment]
I see. Perhaps this is out of scope for you but just to throw an idea out there, it may be possible to generate `m3u8` playlist on the fly which would list all of the `.ts` files. I'm not sure whether Stremio can handle that, but I can give it a try.
