### ISSUE TITLE
Use RD-encoded streams at different bitrates depending on connection speed 

### ISSUE THREAD

**Issue by marco-calautti** [TheBeastLT/torrentio-scraper#203]
The Stremio+torrentio+RD combo is perfect for in-home streaming, where a good connection is available.

However, on the go, high speed connection is not always available, and in many cases, an episode/movie has only a few cached links, which are all too large to stream on slow connections.

Since RD supports on-the-fly re-encoding at different bitrates in it's streaming player, I was wonder whether torrentio could use that feature to request a cached link at a lower bitrate. This ideally could be done dynamically depending on connection speed. But it would also be enough to provide separate links for different bitrates (this could be customizable like quality and size), so the user can choose the desired bitrate manually.

What do you think?

**Comment by TheBeastLT** [comment]
That's outside of the scope for an addon, it only provides link to the video stored in debrid services and doesn't measure client download speed. For such features I'd suggest to then use RD website directly.

**Comment by marco-calautti** [comment]
I respect your choice to not implement it, but then also sorting by file size/quality should be out of the scope of the addon. The bitrate value is something that could be at the same level of quality and size. If choosing it dynamically is out of the scope, then adding it as an additional sorting parameter could remain in scope.

**Comment by phl3g** [comment]
@marco-calautti That is not true. File size and quality is something that you can scrape and get from the torrent during the search phase while for the bitrate you would have to inspect the video file to get the bitrate information. Sure you could calculate average bitrate from size and length but I don't really see the point of that. Just setup another account with lower file size limit for situations with lower connection speeds or edit it on the fly if having issues.

**Comment by marco-calautti** [comment]
> @marco-calautti That is not true. File size and quality is something that you can scrape and get from the torrent during the search phase while for the bitrate you would have to inspect the video file to get the bitrate information. Sure you could calculate average bitrate from size and length but I don't really see the point of that. Just setup another account with lower file size limit for situations with lower connection speeds or edit it on the fly if having issues.

I think there is a misunderstanding on what I was proposing. By bitrate I am not talking about the bitrate of the actual file, but to request to RD to re-encode the file to a desired bitrate before streaming, so to reduce bandwidth usage (e.g., on mobile connections).
This is what the video player of Real Debrid allows you to do before streaming it. I guess RD's API exposes a way to request the file at a desired encoding. 

This procedure does not require checking anything on the file itself, but should be doable by just using the right API call.
