### ISSUE TITLE
[Guidance] How to correctly get anime metadata

### ISSUE THREAD

**Issue by hyoretsu** [TheBeastLT/torrentio-scraper#204]
Hey, I was looking to self-host Torrentio and ended up discovering [stremio-jackett](https://github.com/aymene69/stremio-jackett) and Jackett itself. I like their approach better, and it works better for self-host when you don't have past uptime at your favor, but I'm looking to improve on that addon because currently it gets anime metadata from Cinemeta, and hence only searches for their english titles. Could you share how you circumvented that?

I found some things, like where you use Kitsu's strem.fun in [metadata.js](https://github.com/TheBeastLT/torrentio-scraper/blob/master/catalogs/lib/metadata.js), but I couldn't find how to identify that it's an anime and how to get the Kitsu ID.

**Comment by TheBeastLT** [comment]
It's based on provider and it's categories, but it's beyond of the scope of this repo.
