### ISSUE TITLE
Add Wolmax4k.com as a torrent provider in Spanish (from Spain)

### ISSUE THREAD

**Issue by duda1972** [TheBeastLT/torrentio-scraper#205]
Hello and cordial greetings.

 Wolfmax4k.com is probably the torrent website in Spain that keeps the most up to date.
 All uploads on the website are of great quality and always in Spanish from Spain.

 Please and thank you.

**Comment by sbriongos** [comment]
dontorrent is another one that has a lot of Spanish content.

**Comment by duda1972** [comment]
Hi again, everybody:

 There is a bot on Telegram that uploads Wolfmax4k.com torrents automatically, although I don't know if there is any possibility of linking the channel with Tottrentio.
Torrent Drawer V3 https://t.me/+1ynLrDufsiY1YzA0

 BTDigg DHT Search Engine https://btdig.com/ also keeps torrents updated as they appear on Wolfmax4k.com

 Thank you and goodbye.


 NOTE: Dontorrent, Mejortorrent and many other similar websites limit themselves to re-uploading Wolfmax4k.com torrents days later.

**Comment by duda1972** [comment]
My most sincere thanks.
