### ISSUE TITLE
Can't browse all video files in RealDebrid cloud upload

### ISSUE THREAD

**Issue by Quantumishard** [TheBeastLT/torrentio-scraper#206]
Hello, I have uploaded every episode of The Colbert Report to my Real Debrid cloud, as the formatting of the season/episode structure makes it so that it cannot be scraped from Cinemeta. However, when I browse the upload via the Others section, it only shows about 50 of the nearly 900 video files. Is there a limit to how many can be browsed? I also have every episode of Saturday Night Live, and have no issue browsing those, although there are less of them.

Thank you!

**Comment by TheBeastLT** [comment]
No, it's not limited and returns all video files that are available in the entry.
