### ISSUE TITLE
Torrentio down

### ISSUE THREAD

**Issue by KvHx** [TheBeastLT/torrentio-scraper#209]
Add-on is stuck loading. Is there any indication of issues on the backend?

**Comment by sadie2099** [comment]
Having the same issue

**Comment by ericvlog** [comment]
Yup,it down yet very slow loading.....

**Comment by kubo6472** [comment]
What's considered "the backend" here?

**Comment by dashnak** [comment]
Same over here.

**Comment by pierreleripoll** [comment]
seems to be up again :)

**Comment by KvHx** [comment]
Another outage right now.

**Comment by defalt2003** [comment]
> Another outage right now. Are you able to look? @TheBeastLT

Same here was just watching stremio and reloaded the app and now its not working again
I keep getting 2 addons are still loading issue which is annoying

![image_2024-01-28_031915726](https://github.com/TheBeastLT/torrentio-scraper/assets/151080416/24d88983-732b-4341-83f9-8c47b6778a61)

**Comment by Dyras** [comment]
@TheBeastLT 
If this is a matter of money, give a donation link and my monthly donations you shall have!

**Comment by TheBeastLT** [comment]
#199
