### ISSUE TITLE
Create a self hosted version of the back-end

### ISSUE THREAD

**Issue by grumpyoldman-io** [TheBeastLT/torrentio-scraper#210]
Fellow engineer here, I would be happy to help, but it appears this repo is a bit light on documentation on how to run the back-end. Would you be open to getting some support on building this? Perhaps a good first step would be to add a docker-compose file that allows a dev to run this locally.

To keep the plugin under your control, I would suggest to add the option to point it to a self hosted back-end possibly, so people can choose to roll their own backend, offloading the costs for you.

**Comment by kubo6472** [comment]
Hey, no need to worry, here is it done: https://github.com/Gabisonfire/torrentio-scraper-sh

**Comment by grumpyoldman-io** [comment]
Thanks @kubo6472, I'll close this issue.
