### ISSUE TITLE
Providers not returning correct search results

### ISSUE THREAD

**Issue by matts8008** [TheBeastLT/torrentio-scraper#213]
Torrentio fails to find the show "1000-lb Sisters" (S05E03 to be exact) on multiple torrent providers except TPB, despite the show being available on many providers and all providers selected in Torrentio options.

**Steps to Reproduce:**
Open Torrentio.
Search for "1000-lb Sisters" (S05E03)
Observe results only from TPB.

**Additional Information:**
Other shows do not exhibit this issue.
Issue seems specific to "1000-lb Sisters."
This seems to be related to metadata

PS: Thanks for the awesome app - your hard work is appreciated. Set up a Patreon please.

**Comment by TheBeastLT** [comment]
The main source for this show is eztv and there it's metadata is mapped to incorrect imdbID https://eztvx.to/shows/42502/1000-lb-sisters/
For now I'll block this imdbId so that it would find the correct one via search.
