### ISSUE TITLE
Refresh Debrid Library 

### ISSUE THREAD

**Issue by jhedfors** [TheBeastLT/torrentio-scraper#221]
I would like a way to refresh the Real Debrid Library.

If I update my Debrid Library outside of Stremio, the only way to pick up those changes is to force-stop the app and clear cache.

It does not appear that Stremio is willing to add manual refresh to the app:

https://github.com/Stremio/stremio-features/issues/706#issue-2110840719

I was thinking Torrentio could either automatically refresh the data when entering the (Real) Debrid - Other section, or there could be a new Refresh Debrid Library button.

**Comment by TheBeastLT** [comment]
Currently it refreshes every 20 minutes. At some point I had this without any cache, but it generated too much traffic so I've added some cache time to reduce it.
