### ISSUE TITLE
Delete Magnet Links from RD Cloud after being watched and added

### ISSUE THREAD

**Issue by tundrablasen** [TheBeastLT/torrentio-scraper#225]
This request was already added to you and you did not prioritized it. but it seems that the popularity of your addon/script and the usage of stremio now create massive issues for the CDN Backends.

last night Real-Debrid went down because of it:

![image](https://github.com/TheBeastLT/torrentio-scraper/assets/46343142/868ce579-ee01-4697-8149-fd7e95bfd4ff)

**Comment by TheBeastLT** [comment]
Torrentio has worked with RD for a long long time and it was never a bad actor in the ecosystem, as it only adds a single torrent a user watches. This specifically talks about scripts and addons that add a bunch of torrents at the same time, which is not smth done with torrentio.
