### ISSUE TITLE
Index issue: Poor things 4K RD links missing

### ISSUE THREAD

**Issue by Alphamen16** [TheBeastLT/torrentio-scraper#226]
As the title says, the movie Poor Things is missing it's 4K sources (at least SDR versions, my Torrentio configuration removes HDR/DV etc) but it does index all the 1080p versions.

Considering all the popular torrent sites have 4K versions available for at least 24hours or more, it indicates to me that it's not scraping properly.

Hope it's an easy fix!

**Comment by TheBeastLT** [comment]
Check your addon configuration, there are multiple 4k links.

**Comment by Alphamen16** [comment]
@TheBeastLT not sure if coincidence or not but they are now showing and i did absolutely nothing. Maybe just a caching issue, all good
