### ISSUE TITLE
No streams were found

### ISSUE THREAD

**Issue by a4h7** [TheBeastLT/torrentio-scraper#227]
As title says.

Searching for episodes of a show that is definitely available on TPB but when trying to find an episode on Stremio it's not showing any options.

Thanks

**Comment by TheBeastLT** [comment]
Please provide the exact movie/episode you're trying to get streams for. But it's possible that your configuration is excluding some streams and you're not seeing anything

**Comment by a4h7** [comment]
American Pickers season 25 episode 8
![Screenshot_20240301-001934](https://github.com/TheBeastLT/torrentio-scraper/assets/31749525/446667ce-8ccf-4e85-98bb-d4539e940e80)

**Comment by TheBeastLT** [comment]
It's a metadata problem, not torrentio problem, since there's no metadata in stremio that provides this show in 25 seasons. Cinemeta provides a meta where the seasons are numbered as years, and TMDB addon provides only a meta that has 20 seasons.

**Comment by a4h7** [comment]
I figured it was related to something like that. Do you know how I can
solve the problem?

Thanks

**Comment by TheBeastLT** [comment]
Sadly no, you'd need some meta provider that provides it in 25 seasons, but I don't see a provider that would do that.
