### ISSUE TITLE
Failed to create transcoder

### ISSUE THREAD

**Issue by bastiencyr** [TheBeastLT/torrentio-scraper#23]
Hello, 

I have set up stremio on my own server with yarn ([stremio (master)]( https://github.com/Stremio/stremio-web/tree/master) ) and Nginx. I installed 123movies and torrentio. Movies from 123movies works (not all the time) but movies from torrentio never works.
I have always the same error (Failed to create transcoder). 
It seems that I missed something during the installation of stremio but I don't know what. For example, I can't create an account either, I have to log in as a guest.

Thanks for helping !

**Comment by TheBeastLT** [comment]
Hi, this is not related to Torrentio addon, you should seek help from Stremio developers. But you used  `stremio-web`, which is still in experimental phase, and it supports only web ready formats (https links with mp4/hls), to use torrent streams with it you also need to run Stremio app or standalone stremio server (there's a community docker image https://github.com/sleeyax/stremio-streaming-server) and point to it in `stremio-web` (not sure sure on the details, as haven't set it up myself).
