### ISSUE TITLE
Excluding everything except HDR in the filters shows only 1080p content

### ISSUE THREAD

**Issue by billw1** [TheBeastLT/torrentio-scraper#230]
I'm surprised the only mention I can find of this is in a reddit thread from months ago and everyone telling OP he is wrong. Is this not reproducible? or does nobody care?

If it is true, would love to see it fixed.

**Comment by TheBeastLT** [comment]
Not sure I understand the issue. If you've selected everything to exclude except HDR, then you won't see anything as that means you've also selected to exclude 4k, which almost exclusively have HDR. There might be a few 1080p hdr cases, but that's rare.

**Comment by billw1** [comment]
I see, however; if I include 4k/1080 then I get a mix of SDR/HDR content. My goal was to just show HDR first, then a second instance of Torrentio with SDR only.

**Comment by TheBeastLT** [comment]
I've changed the sorting a bit to prioritise HDR (or DV) links before ones for the same resolution without it, so should help with your use case.
