### ISSUE TITLE
Torrentio RD buffering issue

### ISSUE THREAD

**Issue by celozzip** [TheBeastLT/torrentio-scraper#234]
Is it possible to set the buffer size/streaming speed when using Torrentio RD? 

Sometimes if I load an RD+ link in Stremio it can still have buffering issues. I know my connection is fine because the the same file (or higher bitrate ones) played right off my RD account in PotPlayer (Accessing RD via WebDAV) always work perfectly. In fact I can see the buffer fill up so fast in the seekbar, as it's using all of my connection, that it has downloaded the entire file after just a few minutes of streaming so by then I'm just reading the file off my harddrive. 

Also, the network status panel in the bottom right of the Stremio player is always showing Stream Speed: 0kbps and Buffered: 100MB but I guess that's a limitation of it being designed for showing torrent information?

**Comment by TheBeastLT** [comment]
Addons cannot control anything in the player, so this is outside the scope of any addon.

**Comment by celozzip** [comment]
how does connection to realdebrid work then i thought the addon was responsible for that?
