### ISSUE TITLE
When using VPN, I am blocked from the site. Without a vpn, I am fine. 

### ISSUE THREAD

**Issue by nasawyer7** [TheBeastLT/torrentio-scraper#235]
I'm not exactly sure where to post this, hopefully this is the right spot. 
I created a free vpn with a vps using oracle. I've been trying to use torrentio with it, and it does not work. When I deactivate the vpn, I can stream and search for new torrents just fine. However, I cannot search or access the https://torrentio.strem.fun/configure page without turning off my vpn. When I try to access the website, it tells me I am blocked, and cloudflare says to email the owner.  This is  frusterating, since I cannot safely torrent without turning on and off my vpn multiple times. I was wondering if there was any chance I could get it unblocked? My cloudflare ray id is: 
86c3c7914d5b78e6,
and my vpn ip address starts with 129.146.xx.xx. I can fill in the last two numbers if neccessary, just excluding them so the post does not get taken down. The actual adresss is secure, so I have no issue with releasing the ip address to the public, as I can just switch it if there is any ddos issue easily.

**Comment by TheBeastLT** [comment]
That's a problem with your vpn not the addon.

**Comment by nasawyer7** [comment]
> That's a problem with your vpn not the addon.

My vpn works everywhere else, any ideas on what the fix is/what I can do? 

Here is a screenshot of me getting blocked aswell:
![image](https://github.com/TheBeastLT/torrentio-scraper/assets/103907690/a4910caf-4b0f-4147-b751-bc35bb9d9427)

**Comment by TheBeastLT** [comment]
Not sure, I won't be able to help you here. Maybe try a different vpn.
