### ISSUE TITLE
Max Results Per Quality - Allow 1 per debrid service

### ISSUE THREAD

**Issue by thomasmormay** [TheBeastLT/torrentio-scraper#237]
Some of us use 2 debrid services with Torrentio. 

For example I use both RD & AD. This is because sometimes one goes down and you can sometimes find rare shows on one but not the other.

I have Max Results Per Quality set to 1 to make it easy for my household. It would be awesome if you can set it to 1 per debrid. So, for example it would show 1 RD link & 1 AD link for 4k. Then 1 RD link & 1 AD link for 1080. Etc. That way when one goes down - the other option is there.

**Comment by TheBeastLT** [comment]
That's quite a niche use case and you can always configure 2 instances of addon - one for RD and another for AD.
