### ISSUE TITLE
Excluding Dolby Vision still shows HDR DV files

### ISSUE THREAD

**Issue by Camlan1** [TheBeastLT/torrentio-scraper#239]
The goal is to exclude Dolby Vision files, but still include HDR, since some devices (such as Firestick 4K Max) do not work with HDR + DV, but can work with either.

Better yet, adding an option to only exclude HDR + DV, but keep results that have either one would be nice. It is kind of a niche issue though, mainly for Firestick users.

**Comment by TheBeastLT** [comment]
That's a device issue and too niche to include it as a config option.

**Comment by Camlan1** [comment]
Is it actually the intended behaviour to show HDR + DV files when excluding DV?
