### ISSUE TITLE
[Feature Request] Filter for audio type

### ISSUE THREAD

**Issue by Camlan1** [TheBeastLT/torrentio-scraper#240]
Some devices don't work well with some audio types. One example is Firestick 4K Max with DTS-HD. I also don't like using 7.1 surround sound since the dialogue is usually quiet compared to the rest of the audio.

One annoying thing about audio sources and file names is even though there's DTS-HD in the name of some videos, they may have a second source with AC3. Most 7.1 videos include a backup 5.1 track for audio. I understand that it's not feasible to download part of the source to find out which audio tracks are included.

**Comment by TheBeastLT** [comment]
Similar to https://github.com/TheBeastLT/torrentio-scraper/issues/64
