### ISSUE TITLE
Change the max file size filter to a bitrate filter or size per hour

### ISSUE THREAD

**Issue by Camlan1** [TheBeastLT/torrentio-scraper#241]
Using a set size for a movie or TV show doesn't really work when there's many different runtime lengths.

All I'm concerned about is what the average bitrate is compared to my internet speed.

I guess the existing filter does have a purpose for people with limits to their internet usage per month, and not the speed?

**Comment by TheBeastLT** [comment]
I don't think this will be added, a similar request was answered here https://github.com/TheBeastLT/torrentio-scraper/issues/79#issuecomment-1272579637
