### ISSUE TITLE
Release with a lot of seeders not shown.

### ISSUE THREAD

**Issue by IDontKnow218** [TheBeastLT/torrentio-scraper#243]
Trying to download an anime (Fairy Tail) using Nyaa provider and the release I use all the time (Judas) is not on the list for some reason. It has 80 seeders, and I filtered it show releases with most seeds. Any fix?

**Comment by TheBeastLT** [comment]
Provider exact titles/links and episodes of what you're not seeing.

**Comment by IDontKnow218** [comment]
> Provider exact titles/links and episodes of what you're not seeing. 

Title: Fairy Tail

Release link: nyaa(dot)si/view/1203087

Episodes: All of them

I also discovered that not only the first season has the problem, but also the second and third.
