### ISSUE TITLE
Release with a lot of seeders not shown (again)

### ISSUE THREAD

**Issue by IDontKnow218** [TheBeastLT/torrentio-scraper#244]
So it happened again. Trying to download Fairy Tail (this time season 2) using Nyaa provider and the release I use all the time (Judas) is not on the list. It has lots of seeders, and I filtered it to show releases with most seeds. Please fix it like you fixed season 1.

Also it seems the final season also has the same problem.

**Comment by IDontKnow218** [comment]
Title: Fairy Tail (season 2 and final season)
Release link: nyaa(dot)si/view/1203087
Episodes: Not all of them in Season 2 (Episodes 1 and 2 only). All of them in Final season.

**Comment by TheBeastLT** [comment]
Do not spam with same issues, responses are cached, so if you've viewed links for some episode you'll have to wait until they expire (can take up to 4hrs)
