### ISSUE TITLE
option to remove m2ts links from showing up

### ISSUE THREAD

**Issue by KavGoat** [TheBeastLT/torrentio-scraper#247]
Since Stremio cannot handle m2ts links, it would be great if there was an option to stop them from showing up. Not sure if Torrentio can see whether a link m2ts or not.

**Comment by TheBeastLT** [comment]
Tho some player can play them, so atm I don't plan to exclude them.

**Comment by KavGoat** [comment]
Could it be an option tho? Like a tick box when setting up torrentio. We can include/exclude if we want. Just like we can exclude HDR etc if we want to.
