### ISSUE TITLE
Add support for sports event torrents (mma/boxing/etc)

### ISSUE THREAD

**Issue by godofsword45** [TheBeastLT/torrentio-scraper#250]
MMA and boxing torrents are available in the typical locations, but Torrentio in Stremio is showing "no streams were found".  Please add support for scraping these sports event type torrents.

**Comment by TheBeastLT** [comment]
What typical locations are you talking about? These events are usually hard to match to an imdbId, so often they get mismatched, so not much I can do in an automated system.
