### ISSUE TITLE
Missing Filename from extraArgs When Using Real Debrid

### ISSUE THREAD

**Issue by Nitzantomer1998** [TheBeastLT/torrentio-scraper#251]
Hi,

I have a request. I noticed that when using Torrentio the regular way (without Real Debrid, etc.), the filename is included in the Stremio route of extraArgs, as expected.

However, when using Torrentio with Real Debrid, the filename is not included.

Could you update it to include the filename in this scenario?

I encountered this issue while testing my subtitles addon, which finds the most suitable subtitle for the content being watched based on the filename. It works correctly with the regular version of Torrentio because the filename is included in the extraArgs, but it doesn't work with the Real Debrid option because the filename is missing.

if its can't be done i would like to know about an alternative way to obtain the filename if you know how.
I posted my problem in [Reddit](https://www.reddit.com/r/StremioAddons/comments/1d05vyr/obtaining_filename_from_extraargs_when_using_real/) for more information.

**Comment by TheBeastLT** [comment]
This is not related to the addon and will depend on which platform you're using Stremio and which version, as it was quite a recent addition to support this in some clients AFAIK.

**Comment by Nitzantomer1998** [comment]
Alright, well first thank you for your answer much appreciated.

if you don't mind i have application for providing subtitles to stremio and its using the filename in order to find the best possible subtitles.

because i cant get the subtitles from stremio (i`m getting it if using torrentio without Real Debrid) you know how can i might get the filename which the user use ?
some api route or something ?

**Comment by TwilightMercy** [comment]
![image](https://github.com/TheBeastLT/torrentio-scraper/assets/29895680/d9541d3d-ccfa-42be-a9dd-a13b09374bcb)


https://www.reddit.com/r/StremioAddons/comments/1d05vyr/obtaining_filename_from_extraargs_when_using_real/

**Comment by TwilightMercy** [comment]
> This is not related to the addon and will depend on which platform you're using Stremio and which version, as it was quite a recent addition to support this in some clients AFAIK.

Hi @TheBeastLT,

Please refer to:
https://github.com/Stremio/stremio-addon-sdk/pull/249/commits/60b81f4fd311259176035cbc4e7becdade5eb7fb

Stremio support getting playing filename/RD stream URL through extraArgs
