### ISSUE TITLE
Ability to Choose how Torrents will Display

### ISSUE THREAD

**Issue by Jesuninfinity** [TheBeastLT/torrentio-scraper#252]
Feature request

Kindly add the ability to display Parsed Data only. The most helpful data to display would be:

(Quality, Resolution, Codec, Audio info, HDR info, Subtle info, File Size. )

Looking forward to a favorable response. 

![IMG-20240529-WA0004](https://github.com/TheBeastLT/torrentio-scraper/assets/115922842/5f921e5d-b67f-41e6-8e1e-1acadda5f0a3)

![IMG-20240529-WA0005](https://github.com/TheBeastLT/torrentio-scraper/assets/115922842/a84bd1bd-3120-49e7-8459-68b98f9ba452)

**Comment by TheBeastLT** [comment]
No Plans for such a feature.
