### ISSUE TITLE
Seedr and Pikpak integration

### ISSUE THREAD

**Issue by SanthoshAnbalagan** [TheBeastLT/torrentio-scraper#254]
Hi @TheBeastLT , I hope this message finds you well. I wanted to suggest adding Seedr and Pikpak support to Torrentio. This feature would be incredibly beneficial for users who do not have a debrid subscription. Mediafusion currently offers this functionality, and it would be fantastic to see the same in Torrentio.

**Comment by TheBeastLT** [comment]
Duplice #178 #223
