### ISSUE TITLE
Torrent loading problem 

### ISSUE THREAD

**Issue by adilurrhmn** [TheBeastLT/torrentio-scraper#255]
A torrent is already present in torrent websites ( 1337x, torrent galaxy) but in stremio it shows blank

![Screenshot_2024-06-14-22-06-56-70_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/TheBeastLT/torrentio-scraper/assets/124466769/b46b5c26-d469-46df-857b-8e0019898529)

![Screenshot_2024-06-14-22-06-23-76_5a1e11fa41055108da81eb54eea93a2a](https://github.com/TheBeastLT/torrentio-scraper/assets/124466769/0cbb96d4-fd18-4df4-9fd7-b307f7776dab)

**Comment by TheBeastLT** [comment]
There was an issue with the 1337x scraper. Thanks for letting me know.

**Comment by adilurrhmn** [comment]
Thank you 👍
