### ISSUE TITLE
Filename Missing in ExtraArgs with Real Debrid

### ISSUE THREAD

**Issue by Nitzantomer1998** [TheBeastLT/torrentio-scraper#256]
Hi,

I wanted to let you know that the filename is not being sent in the Real Debrid version. I would appreciate it if this could be addressed so It will be easy to choose the optimal subtitle quickly.

As you can see, for the free version, it works fine:
![Without-RealDebrid](https://github.com/TheBeastLT/torrentio-scraper/assets/93198738/f55ce103-bfed-4c3b-8d05-5b027af314fb)

But for the Real Debrid option, the filename isn't sent back:
![With-RealDebrid](https://github.com/TheBeastLT/torrentio-scraper/assets/93198738/729e1f50-bf66-47af-9313-891717020b9d)

This information is provided from your addon through Stremio. I hope you can find and resolve the problem, as the filename needed to quickly find the suitable subtitle (through a script).

Thank you for the awesome addon!.

Note: I know the both torrents in the video are not identical, i couldn't see it in the free version as it not loaded. but the problem remain the same through all the torrents

If needed information here's Stremio official commit for this change: [#60b81f4](https://github.com/Stremio/stremio-addon-sdk/commit/60b81f4fd311259176035cbc4e7becdade5eb7fb)

**Comment by TheBeastLT** [comment]
Everything is implemented according to spec from addons side. It will depend on the stremio client platform and version you're using and whether it supports the new spec.
