### ISSUE TITLE
No streams found on new account

### ISSUE THREAD

**Issue by raunakbhojwani** [TheBeastLT/torrentio-scraper#258]
I'm having a strange issue where my old Stremio account is retrieving Torrentio links as [RD+]. However, on my new account installing the Torrentio addon shows "No Streams Found". It's the exact same addon, configuration and API key as my older account. I've even tried creating a new RD key and new Stremio account to use but that was not the problem. Can you please help me figure out why this is happening? Is this a recurring issue for newer installs?

**Comment by TheBeastLT** [comment]
Probably some configuration issue on your side. Make sure to not check `Non 3D` quality exclude filter, as it will exclude all of sources except 3D ones.

**Comment by raunakbhojwani** [comment]
Thank you, you were right. When I first set it up, it did not have the 3D and non 3D filter types. I was excluding both.
