### ISSUE TITLE
Torrentio issues linking to all debrid key

### ISSUE THREAD

**Issue by faeem-mahommed** [TheBeastLT/torrentio-scraper#259]
Hi there 
I have an issue were my all debrid keys can pull cached files from other addons but not torrentio.
Is there a particular reason why.
Used to work but no longer does.
Every key generated on all debrid works with say media fusion to bring back addon results.
But with tortentio it’s an immediate no streams found.
This is for new content and old 
And used to be aces

**Comment by TheBeastLT** [comment]
Make sure you are not selecting smth not intended in quality exclude filter.

**Comment by faeem-mahommed** [comment]
apologies sir
not understanding what’s smt
which option is that in the quality drop down?

Regards,
Feemo
________________________________

**Comment by faeem-mahommed** [comment]
me again

have only selected 1080p in quality filter

add on gets added to stremio

doesn’t get fetched when pulling up a show

does so for the likes of torrentjacket and media fusion though

Regards,
Feemo
________________________________

**Comment by TheBeastLT** [comment]
Uninstall all previous configurations of Torrentio from you addons, and then install a fresh configuration where the only thing you change is enter your RD api key, nothing more. And see if that helps.

**Comment by faeem-mahommed** [comment]
thanks guys that helped looks like the quality filter poked the actual add on

Regards,
Feemo
________________________________
