### ISSUE TITLE
Add Dontorrent as a torrent provider.

### ISSUE THREAD

**Issue by duda1972** [TheBeastLT/torrentio-scraper#261]
Hello again:

 In the search for constant improvement of Torrentio I propose to complement 
torrent providers with the addition of Dontorrent.

 Dontorrent is a stable and trustworthy website that has been in operation for a long time.

 Official Domains - DonTorrent https://dontorrent.city/dominios
 DonTorrent (Official Channel) – Telegram
https://t.me/DonTorrent

 Please and thank you.

**Comment by TheBeastLT** [comment]
Duplicate #260
Use search before opening new issues

**Comment by duda1972** [comment]
Sorry for the inconvenience, it is far from my intention to waste your time but in my opinion the duplicate request reflects the sincere interest of Torrentio users. 

 In any case, I want to take this opportunity to thank you once again for having added Wolfmax4k to the torrent providers.

🤗
