### ISSUE TITLE
Insight on adding support  for music?

### ISSUE THREAD

**Issue by darcyvdd** [TheBeastLT/torrentio-scraper#263]
I'm looking into building a stremio add-on to load music catalogues (user defined playlists from separate services, trending etc. and scrobbling). Would love people to be able to stream their music through torrentio however only movie and series types are supported at the moment. Would you guys be open to adding in support for music or accepting PRs regarding that?

Cheers for taking the time to read this

**Comment by TheBeastLT** [comment]
No plans to add music to Torrentio, that's a completely different domain. I know that there was once a torrents music addon created by a dev called rab1t on stremio discord.
