### ISSUE TITLE
Torrentio Rutracker 

### ISSUE THREAD

**Issue by polischuk16** [TheBeastLT/torrentio-scraper#265]
Today while using stremio and torrentio I was not able to play any source from rutracker. Terrentio finds sources but not loading anything. It was working just fine for the past year or so.
I tried on a few different streaming boxes, different networks, with and without vpn. Very strange. Hopefully it can be fixed soon.

**Comment by TheBeastLT** [comment]
This is just an indexer, it doesn't serve or store any of the content. Any torrent related issues are on your side.

**Comment by polischuk16** [comment]
> This is just an indexer, it doesn't serve or store any of the content. Any torrent related issues are on your side.

Not true. I can access rutracker from my devices and I can still play any other torrent source through stremio no problem. Only rutracker source refuses to load.

**Comment by TheBeastLT** [comment]
Feel free to create your own addon that fixes your problems if you're so sure about how everything works.
