### ISSUE TITLE
Downtime

### ISSUE THREAD

**Issue by Unsliced9980** [TheBeastLT/torrentio-scraper#268]
Torrentio experiencing long period of downtime over the past few days. Not sure if it's related to #199 but thought I'd open a new issue on here just in case. Appreciate your work!

**Comment by TheBeastLT** [comment]
There are abusive clients (other than stremio) that abuse this freely hosted addon using various proxies and other IP changing services which makes it quite hard to deal with on my free time. For now it is how it is, until there's a better solution (maybe introduce account system in torrentio).
