### ISSUE TITLE
Contributing, and the Database

### ISSUE THREAD

**Issue by wMarciano** [TheBeastLT/torrentio-scraper#270]
Firstly, @TheBeastLT, thank you for developing and hosting such a wonderful project. 

The community thrives because of you, and many of us would love to give back by contributing to the project. While this is very possible, the (understandably) locked-down database makes it challenging to test changes. 

Since the DB is private for DMCA reasons, how about releasing an extremely cut down version with only a few public domain titles? You could even just do 1 movie and 1 series, like _'The Kid'_ (tt0012349) & _'The Beverly Hillbillies'_ (tt0055662) **ONLY Season 1 + 2.** That way, devs have a way to test on both media types.

Please consider! I'd be happy to make docs and whatnot to facilitate contribution, this project has potential like no other!

**Comment by TheBeastLT** [comment]
Hi, due to the nature of this addon I'm not seeking community help on expanding it's functionality (since it's pretty much stable feature wise). Because of this available features are heavily opinionated and should be as simple as possible (that's one the the key points of stremio)
