### ISSUE TITLE
[Not an issue] Just a question

### ISSUE THREAD

**Issue by razeNFR** [TheBeastLT/torrentio-scraper#273]
Hello,

I just wanted to know if it is possible to make the Torrentio "scrapper" completely Open-Source, because it is in my opinion the best optimized and most efficient addon on Stremio but it is a shame not to be able to use it personally to put your own private trackers and also to be able to keep Torrentio alive if ever one day you decide to no longer maintain it.

That's it, it was just a question.

Thanks in advance for your answer.

_(PS: Im bad in english, so i used Google Translate to make this post)_

**Comment by erynith** [comment]
I personally think the scraper should only be open source once it's no longer maintained

**Comment by razeNFR** [comment]
> I personally think the scraper should only be open source once it's no longer maintained

Why you personnaly think that ?

**Comment by TheBeastLT** [comment]
https://github.com/TheBeastLT/torrentio-scraper/issues/113
