### ISSUE TITLE
[QUESTION][PROVIDERS] Add yggtorrent

### ISSUE THREAD

**Issue by tellitrack** [TheBeastLT/torrentio-scraper#274]
Hello.

As the scraping seems to be server side, would it be possible to add the provider yggtorrent ? This will require user credentials. But i was wondering if it would be possible. 
Unfortunately even if this add-on is amazing i frequently not find french version of torrent while it's well on yggtorrent (www.ygg.re). 
Thank you :)

**Comment by TheBeastLT** [comment]
This is a private tracker, and this addon only deal with public ones, as scraping and serving content for public AND private ones would be difficult.
