### ISSUE TITLE
using a different IP

### ISSUE THREAD

**Issue by tgmb1** [TheBeastLT/torrentio-scraper#275]
![20240917_054809](https://github.com/user-attachments/assets/4087461c-a1cf-48c5-846e-fd40b005b98f)

All other add-ons except TORRENTIO use the long wifi IP same as one saved in REAL DEBRID  my account section 
torrentio uses 103.xx.xxx.xx IP

Because of this , even on using multiple devices in same WiFi, I got a warning

How to make torrent use the same IP as other addons

**Comment by TheBeastLT** [comment]
This is due to the fact, that at the time RD added IP requirements IPv6 did not work and  only IPv4 would. So you had forward user's IPv4 in order for the stream to work. It is resolved by CF and nobody di have problems before. Tho if RD now supports IPv6, maybe this could be changed, but also depends if other debrid providers support it and that might be difficult to know, so probably better strategy would be "if it ain't broke, don't fix it".

**Comment by tgmb1** [comment]
I understand now 
but , please take my request into consideration
I will clearly tell you what happened

I was watching a movie with torrentio in my FIRESTICK 
I have never used multiple devices since I bought RD

But yesterday, I added STREMIO + RD in two other phones connected to same WiFi

I myself , dad and mom were playing different movies in firestick, phone 1 and phone 2.
IMPORTANT : ALL DEVICES are connected to the same WIFI!

even then , RD registered 3 different IPs and gave me warning 
My account is at suspension risk now.

 "if it ain't broke, don't fix it". Please don't say this....

I can't afford multiple RD accounts rn , please fix this so that torrentio uses the same IP as other add-ons and I can use multiple devices with same WiFi

**Comment by TheBeastLT** [comment]
> even then , RD registered 3 different IPs and gave me warning

This leads me to believe there was some issue on your end, as it's then not possible to have 3 different IPs. Same IPv6 will always resolve to same IPv4, so it's not possible to have such situation. Then either you have multiple APs which have different external IPs assigned or some dynamic IPs, in both of these situations there's nothing that can be changed from addon's side to solve this.

**Comment by tgmb1** [comment]
My Internet Protocol is shown IPV6 in REAL DEBRID account informations ,
and is chosen IPV4 by default in REAL DEBRID account settings.

Should I change to IPV4+IPV6?
![20240918_024631](https://github.com/user-attachments/assets/5a7df102-e6df-4c6f-90f2-592bf6d239f4)

Now , I have set STATIC IP across all my four devices, three mobiles and one FIRESTICK , now torrentio shows the long IP for all devices when using STREMIO , 
but last 5-8 characters are different for each device , now it's safe , right?

**Comment by TheBeastLT** [comment]
> My Internet Protocol is shown IPV6 in REAL DEBRID account informations ,
> and is chosen IPV4 by default in REAL DEBRID account settings.
> 
> Should I change to IPV4+IPV6?
> ![20240918_024631](https://github.com/user-attachments/assets/5a7df102-e6df-4c6f-90f2-592bf6d239f4)
> 
> Now , I have set STATIC IP across all my four devices, three mobiles and one FIRESTICK , now torrentio shows the long IP for all devices when using STREMIO , 
> but last 5-8 characters are different for each device , now it's safe , right?


Best to consult with RD regarding this.
