### ISSUE TITLE
TorrentGalaxy downtime/maintenance missing torrents

### ISSUE THREAD

**Issue by Joerg87** [TheBeastLT/torrentio-scraper#276]
I noticed that there are gaps in torrentio TorrentGalaxy scraping around 20/09/2024 - 21/09/2024 and torrents are missing from the torrentio db. Hope it's possible to re-scrape the missing torrents.

Thank you and keep up the good work!

**Comment by TheBeastLT** [comment]
I think it indexed everything, unless you can share an example?

**Comment by Joerg87** [comment]
From TGx id 16173525 (20/09/2024 07:16) to 16174723 (21/09/2024 13:25).

**Comment by TheBeastLT** [comment]
Reindexed that id range again and some new netries were added. Thanks

**Comment by Joerg87** [comment]
@TheBeastLT There is a new gap in the TGx id 16224xxx (13/11/2024) area. Hope you can re-scrape.

**Comment by TheBeastLT** [comment]
@Joerg87 I've reindexed this range, but no new entries were added, so don't think anything is missing fro tgx. Some entries can be indexed from other providers first, so they might appear under a different provider.

**Comment by Joerg87** [comment]
@TheBeastLT Is TorrentGalaxy scraping currently down? Since the site came back up a lot of torrents are missing from the torrentio DB. Example ids 16252394 16254311. Can you re-scrape from 16252000 to now?
