### ISSUE TITLE
Sources for Wolfmax4k torrents

### ISSUE THREAD

**Issue by duda1972** [TheBeastLT/torrentio-scraper#278]
Options to improve Torrentio access to Wolfmax4k torrents:

wolfmax4k - BTDigg DHT Search Engine https://btdig.com/search?order=2&q=wolfmax4k

Cajon de Torrents V4 https://t.me/+K06LBYuA0wNkZTRk

**Comment by TheBeastLT** [comment]
Btdigg added cf captcha, so it's much harder to scrape

**Comment by duda1972** [comment]
> Btdigg added cf captcha, so it's much harder to scrape

hello, I just want to ask if you can publicly share the method used to overcome the cf captcha of btdigg so that other addons similar to torrentio have access to wolfmax4k torrents again

please and thank you

**Comment by duda1972** [comment]
> Options to improve Torrentio access to Wolfmax4k torrents:
> 
> wolfmax4k - BTDigg DHT Search Engine https://btdig.com/search?order=2&q=wolfmax4k
> 
> Cajon de Torrents V4 https://t.me/+K06LBYuA0wNkZTRk

Cajon de Torrents 202410 (V5) https://t.me/+lIz5M_1uzhxlY2Nk
