### ISSUE TITLE
Kamen rider build episodes not showing up

### ISSUE THREAD

**Issue by Miyav-0** [TheBeastLT/torrentio-scraper#280]
![Screenshot_20241015_175527_Opera](https://github.com/user-attachments/assets/8ffc6e7c-3d38-40ce-98cd-e46a417020fb)
![Screenshot_20241015_175538_Stremio](https://github.com/user-attachments/assets/97b96a27-3a3a-4291-bdbf-7916eee2f3d2)

**Comment by TheBeastLT** [comment]
Only English translated anime category is scraped on nyaa. No plans atm to add other categories.
