### ISSUE TITLE
Customize the baseUrl for debrid service?

### ISSUE THREAD

**Issue by MunifTanjim** [TheBeastLT/torrentio-scraper#281]
Is there a way to customize the baseUrl of a debrid service? If not, I can open a PR to contribute the changes necessary if you're open to it.

**Comment by TheBeastLT** [comment]
This is not a local addon, so I dont see a use case where this would be needed. If some debrid url changes then most likely it will need code changes as well, and having just changing url is very niche and obscure setting.

**Comment by MunifTanjim** [comment]
This would've been useful if somebody sets up a reverse proxy for debrid service.
