### ISSUE TITLE
Torrentio not scraping links.

### ISSUE THREAD

**Issue by sinbad1722** [TheBeastLT/torrentio-scraper#284]
I was trying to watch an anime episode released 36 hours ago but torrentio didnt scrape streams, But it did get links in anime kitsu catlogs and anime catlogs. Torrentio when used with other catlog addons takes longer time to scrape after release even though the torrents are already available in the source where torrentio scrapes. I hope it gets fixed.
Thank you
To recreate this issue go to dandadan season 1 episode 5.

**Comment by Stremiogdrive** [comment]
![Screenshot_20241102-070659_Stremio](https://github.com/user-attachments/assets/92f58f5e-9b69-4a9f-b792-5a7fc332a417)
![Screenshot_20241102-070659_Stremio](https://github.com/user-attachments/assets/5d7a9985-b368-4edf-88ff-6cd28f7e60f3)
![Screenshot_20241102-070648_Stremio](https://github.com/user-attachments/assets/4ed1420b-5b67-4e5a-ba9a-aef1a66b16a6)

**Comment by TheBeastLT** [comment]
There was an issue with kitsu api, which is needed to correctly map from kitsu ids to imdb ones
