### ISSUE TITLE
Self hosting

### ISSUE THREAD

**Issue by ShakedGold** [TheBeastLT/torrentio-scraper#289]
Is it possible to self host this add-on and use it in stremio

**Comment by ronfrankhill** [comment]
https://www.ovhcloud.com/en/vps/

**Comment by Munnyo** [comment]
Please tell us if we can help the team with donations to make torrentioRD back online

**Comment by matou78** [comment]
hello, same here, would love to know if this can be self hosted and if the team need some money, i would help too

**Comment by TheBeastLT** [comment]
#113
