### ISSUE TITLE
Alldebrid not playing/Installing post recovery

### ISSUE THREAD

**Issue by Imsaffor** [TheBeastLT/torrentio-scraper#291]
Alldebrid not loading episodes post recovery. Installation fails with AllDebrid API key.

error message displays failed to fetch media in Stremio App

**Comment by sishgupta** [comment]
It was working for about 20 minutes when everything came back up. I submitted a ticket with AD support to see if they can do anything on their end...like allowing the new torrentio host.

**Comment by BRKsays** [comment]
A small update to this issue. The addon now installs with All Debrid configuration as of this moment, but returns no results for any movie or show. No email from AD is received for new IP address confirmation as well.

**Comment by BRKsays** [comment]
Issue seems to be fixed. Addon is installed with AD configuration. When searching for movies and shows, AD+ results are showing up and streaming well

**Comment by andremacola** [comment]
AllDebrid still not working. Not listing AD+ links

**Comment by sishgupta** [comment]
Check your email. I just had to verify an email from AD for the API. Was working before that. But suddenly not and as soon as I was struggling I got an email.

**Comment by andremacola** [comment]
I had to do a complete reinstall and check my email
