### ISSUE TITLE
Access is blocked with Alldebrid and Realdebrid -> Torrentio down?

### ISSUE THREAD

**Issue by Coraggiosoo** [TheBeastLT/torrentio-scraper#298]
<img width="269" alt="image" src="https://github.com/user-attachments/assets/fa0ee6d6-f083-49a1-88d2-95c044ec385b">

First receive this error from Alldebrid, then I created a new account on Realdebrid, but receive the same error message.
Torrentio currently down?

**Comment by TheBeastLT** [comment]
This is a message for Alldebrid integration, which means that you need to confirm access for torrentio addon to access your AD account. Usually you get an email for this.
