### ISSUE TITLE
Unable to add torrentio to streamio with RD

### ISSUE THREAD

**Issue by alexcarinci** [TheBeastLT/torrentio-scraper#299]
Trying to add the Torrentio addon via web or the macos app, I get "failed to get addon manifest from torrentio.strem.fun/... manifest.json" "failed to fetch: network error when attempting to fetch resource"

In the app when using the install link it says "ERROR OPENING MEDIA - Failed to Fetch"

**Comment by TheBeastLT** [comment]
Seems like your network issues, as it fails to access Torrentio. Check with a different network maybe, or try changing yur DNS.

**Comment by alexcarinci** [comment]
Thanks you were correct, it was a dns issue on my end.
