### ISSUE TITLE
Torbox integration request

### ISSUE THREAD

**Issue by Pentonize** [TheBeastLT/torrentio-scraper#301]
Hi, following Real-Debrid's latest post in regards to their laws and the taking down of the API (,https://x.com/RealDebrid/status/1859673163681960169?t=d13BGEonsE4DDP3Yr9QzFw&s=19)

I think TorBox would be a great provider to have as I believe it has a full API setup and has similar features to a debrid manager, along with Usenet.  
Torbox has it's own stremio addon but doesn't have the amount of torrents Torrentio has, so would be cool to see it added!

**Comment by Aresitoo** [comment]
Yes. Please add TorBox.
Thanks Dev

**Comment by TheBeastLT** [comment]
#184
