### ISSUE TITLE
Addon has been moved to a new hosting provider, which will hopefully be more resilient.

### ISSUE THREAD

**Issue by 1e-skip** [TheBeastLT/torrentio-scraper#303]
Addon has been moved to a new hosting provider, which will hopefully be more resilient.

_Originally posted by @TheBeastLT in https://github.com/TheBeastLT/torrentio-scraper/issues/288#issuecomment-2477253359_
            

This ADD-on still doesn't work for me after the last outage 13-11-2024. The strange thing is that it does work for my partner, but I still don't see any results from torrentio in stremio. The only difference is that add-on v0.0.13 is used and I use "torrentio AD 0.0.14". Do more people have this issue?

skip

**Comment by TheBeastLT** [comment]
Check your email, you might need to authorize torrentio access to AD.
