### ISSUE TITLE
Torbox plays the wrong episodes

### ISSUE THREAD

**Issue by i1u5** [TheBeastLT/torrentio-scraper#311]
Something seems wrong with the detection for episodes, selecting a specific link even if it's cached plays the wrong episode (while it shows the correct episode filename in the links), other times it straight up shows a "playback error" message, I think it's related to episodes within complete season torrents (multiple files).

Example: House S02E07 plays S01E07 with the first link, S08E07 with the second and S03E07 with the third, this confirms the first paragraph since a tv show as old as House obviously only has complete seasons/repacks as alive torrents.

On the other hand, Torbox's own addon plays the episodes perfectly fine.

edit: it also sometimes may show all links as [torbox download] and they fail to play of course (I'm pretty sure some of them are cached) but I assume that's caused by the current service outages so maybe torrentio just assumes they're not available.

**Comment by TheBeastLT** [comment]
Was not able to replicate it, for S02E07 all entries return the correct file.  Maybe you're using some self made urls or smth?

Cached status is reported by TorBox so what's reported that's what's displayed.
