### ISSUE TITLE
Many links are marked as 0 seeders

### ISSUE THREAD

**Issue by Atreus93** [TheBeastLT/torrentio-scraper#312]
And most of those links don't appear in torrentio setup with no debrid service. 

1
![Screenshot_٢٠٢٤١١٢٧_١٠٣١٠٦_Stremio](https://github.com/user-attachments/assets/b12bc533-1a96-4a2c-83d0-627b0b4c47cb)
![Screenshot_٢٠٢٤١١٢٧_١٠٣١٠٦_Stremio](https://github.com/user-attachments/assets/1b3514aa-b7b4-438a-8cf7-680043c6b829)

2
![IMG-20241127-WA0000](https://github.com/user-attachments/assets/413de47a-01ac-4666-b987-346c1651ecda)
![Screenshot_٢٠٢٤١١٢٧_١٠٣٤٥٣_Stremio](https://github.com/user-attachments/assets/04b6fe02-a9ce-49f3-a1b6-fd48138a52f6)

So i think this bug makes some links become Zero seedrs 
and that leads to make them (some of them) disappear except in debrid setup. I know it that  it's not right, because suddenly i notice links that i play everyday become have 0 seedrs and, and i can stream them well if i find them in no debrid setup but like i say the problem is most of them disappear. I care about this because Maybe i will have to use torrentio with no debrid if things go worse.. after the events we know about debrid service

Thanks

**Comment by RanNahmany** [comment]
+1

**Comment by TheBeastLT** [comment]
There was a bug in the seeders update logic, which was fixed. Should get back to normal once they are re-updated again.
