### ISSUE TITLE
Torrentio Torbox causes Stremio to crash 

### ISSUE THREAD

**Issue by Adamjr4** [TheBeastLT/torrentio-scraper#315]
I am running Stremio on Fire OS 7.6.7.3 and with Torrentio TB installed, my Stremio app crashes within 2 minutes of streaming a program. 

If I remove Torrentio TB as an official add on, it stops crashing. I've tried every combination of removing add ons, cleared cache, uninstalled and reinstalled, and nothing works except removing Torrentio TB. 

I am still able to stream with the official Torbox add on, which leads me to believe it's somehow related to the new Torrentio TB support. 

I can still use Torrentio RD and that doesn't cause crashes.

**Comment by TheBeastLT** [comment]
Addons cannot crash the app, since they only return json responses. It might crash due to the item you're playing and your device not being powerful enough for it.
