### ISSUE TITLE
Plex Debrid not working with torrentio

### ISSUE THREAD

**Issue by juanmita77** [TheBeastLT/torrentio-scraper#317]
Plex Debrid hooking "0 releases" for every single file I add to wish lists. When scrapping with torrentio always getting 0 releases for any file. 
 This need to be solved ASAP, thanks.
![Captura de pantalla 2024-11-29 163649](https://github.com/user-attachments/assets/fd6a986b-3a5a-4f33-98ae-89154b960335)
![Captura de pantalla 2024-11-29 163649](https://github.com/user-attachments/assets/dfc26746-eb09-463e-9c44-12755efa22a3)

**Comment by TheBeastLT** [comment]
Wrong repo. Solved ASAP.

**Comment by juanmita77** [comment]
> Wrong repo. Solved ASAP.

Excuse me, what do you mean by "Wrong repo"?

**Comment by juanmita77** [comment]
This is the arrogance of developers. They close the question without resolving it and with arrogance. Never forget that we are the users who test your tools. If you're not going to answer me, don't let it be so noticeable.

**Comment by juanmita77** [comment]
which repo is this suppossed to be? At least answer me
