### ISSUE TITLE
Not all [downloads] links shown with AD

### ISSUE THREAD

**Issue by onfire-d** [TheBeastLT/torrentio-scraper#318]
Not all [AD Download] links are shown in Torrentio.
![IMG_7624](https://github.com/user-attachments/assets/6ec9db48-cb54-4f8e-90f7-532fec3af836)
![IMG_7625](https://github.com/user-attachments/assets/5fcee65e-fcbb-4b79-94a0-7fd7fcd2dd02)

In all apps.

**Comment by TheBeastLT** [comment]
That's related to your config, the first SS seems to have you prioritise spanish lang, and the 2nd does not.

**Comment by onfire-d** [comment]
> That's related to your config, the first SS seems to have you prioritise spanish lang, and the 2nd does not.

As you can see the first link of the second config is in Spanish too (4h link in the second screenshot), 3 first are missing.

made sure to check config again and Spanish remains as priority. Checked on my sister’s account and is happening too. (Spanish priority too)
