### ISSUE TITLE
[Feature Request] Exclude uploaders from results

### ISSUE THREAD

**Issue by lalalasupa0** [TheBeastLT/torrentio-scraper#319]
It was honestly surprising to see that no one has opened an issue for this before, and at least I haven't seen any option to do this

There are a lot of trash uploaders, especially on nyaa (but there are also a lot of hella good ones so... It's not like just excluding nyaa itself would be better)
So, I think it would help to list in a more enhanced way excluding those uploaders, how? The best would be to exclude torrents with certain words between [] in titles like *[~~VCB-Studio~~ **(uploader)**] Anime Name (Blabla) [Blabla]* or something like that, I don't understand how it would work so Idk

**Comment by TheBeastLT** [comment]
No plans for such a feature.
