### ISSUE TITLE
Issue with video playback using Torbox.

### ISSUE THREAD

**Issue by jfoz37** [TheBeastLT/torrentio-scraper#324]
Windows 10 Pro, v22H2
Stremio v4.4.168
Torrentio v0.0.14

Torrentio is the only addon installed other than the default Stremio addons.

Using the Torbox pro plan. Sometimes a video will randomly stop playing. Trying to resume it will result in the following message: Playback error, please try again.

So far, almost nothing I have tried will clear that error message and make the video playable again. Any other video file, using the Torrentio addon, will work fine however. At least unless it randomly stops at some point too.

Things I have tried to resolve the issue (basically every bit of "advice" I could find online):

Contacting Torbox and Stremio support (both say it is addon related).
Clearing data/cache in Stremio.
Using a different device (tried a Windows 10 PC and another running Windows 11 24H2).
Uninstalling and reinstalling Stremio.
Uninstalling and reinstalling/configuring Torrentio.
Generating a new API key from Torbox.
Resetting my router.
Using a VPN.
Streaming to VLC instead of the default Stremio player.
Waiting a long time to see if the file will become playable again (it didn't in about 36 hours).

A couple days ago, I would get this playback error message no matter how I tried to play the file, including directly from the seedbox. Today, it seems to work if I go to the "Others - TorBox Torrents" section. But, if I try to open it via the "continue watching" section, or through a search in Stremio, the error message persists.

If I pause the video, or stop it and come back later, I generally don't have many issues. It is only when the video seems to stop on its own. And even then, it doesn't happen every time. Seems like it happens somewhere around 80-90% of the time though.

Intending to share my setup with a couple of senior citizens who know very little about tech and am trying to make it as simple as possible for them. Any help with this issue would be greatly appreciated. I'll be happy to provide any further information may you need as well.

**Comment by TheBeastLT** [comment]
Don't think it's related to the addon, as it has nothing to do with streaming itself. Might be due to some player specific where you keep the same resolved debrid url in the player for 36hr after which it expires or smth and is not usable. Check if you have the same behaviour with other addons which have TB integration.
