### ISSUE TITLE
Stuck Loading on Title Screen

### ISSUE THREAD

**Issue by Prior44** [TheBeastLT/torrentio-scraper#326]
I have been using Stremio for a week with the Torremtio and Comet addons. It was working for a few days but now I am stuck on the loading title screen unable to watch anything. I have a debrid through Torbox and I believe I set everything up correctly. I turned on hardware accelerated decoding, cleared cache, uninstall/reinstall Torrentio and Comet addons and Stremio too. 

The error that appears on my screen says "Playback error. Please try again"

I am stuck and don't know what else I can do

**Comment by TheBeastLT** [comment]
Not related to the addon itself, as the addon is not responsible for the streaming itself. Something's probably with your network.
