### ISSUE TITLE
Feature request - Disable DHT, PEX, LPD

### ISSUE THREAD

**Issue by blaudp79** [TheBeastLT/torrentio-scraper#327]
Hi,

It would be great to have the option to disable DHT, PEX, LPD for users that download torrents directly.

Thanks.

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a new option 'disable_dht_pex_lpd' to the configuration to allow users to disable DHT, PEX, and LPD for direct torrent downloads.

You can review changes in this commit: https://github.com/jacks-sam1010/TheBeastLT-torrentio-scraper-327/commit/812968d5b1674dbdec70b61297e8bb519b3ec3f1.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by blaudp79** [comment]
Awesome. Thanks for the quick response.

**Comment by TheBeastLT** [comment]
No plans for such a feature
