### ISSUE TITLE
API Update Issue: All links marked as [AD DOWNLOAD], none as [AD+]

### ISSUE THREAD

**Issue by Artus13** [TheBeastLT/torrentio-scraper#329]
Hi there,

I believe the AllDebrid API may have changed recently (or some time ago), as I’ve noticed that all links are now marked as [AD DOWNLOAD] and none as [AD+].

Would it be possible to look into this and fix it if necessary? Your work is much appreciated, and thanks in advance for your help!

Best regards.

**Comment by TheBeastLT** [comment]
RD, AD and DL all removed API to checked the cached status, so there's no longer links for AD+, you have to manually try AD Download links and check which are instant streamable

**Comment by TwilightMercy** [comment]
No internal Torrentio cache?

**Comment by TheBeastLT** [comment]
It made sense for RD, since there's a huge user base using it, not so much for AD or DL.

**Comment by TwilightMercy** [comment]
Hi, is is still the same approach for AD?
