### ISSUE TITLE
Torrentio RD not working on Android but Media Fusion works

### ISSUE THREAD

**Issue by BRKsays** [TheBeastLT/torrentio-scraper#331]
1. Torrentio is not working for me on my android device. No matter what I try to play, it always give "Some usage limit exceeded, check your debrid account for more info" error.
2. Media Fusion with RD is working on my android device without any issue.
3. I don't have any pending downloads in RD.
4. Torrentio RD in web Stremio works fine.
5. Since Torrentio is working fine on web version of Stremio and Media Fusion is working fine on Android, the issue shouldn't be with RD, right?

**Comment by TheBeastLT** [comment]
The message is clear enough, you're exceeding some usage limits - `Too many active downloads;Traffic exhausted;Upload too big;Fair Usage Limit`.
