### ISSUE TITLE
[Request] option to filter 3D sources / sort by 3D sources

### ISSUE THREAD

**Issue by trumanhung** [TheBeastLT/torrentio-scraper#37]
As a person who owns a 3D player, I want to filter 3D sources or prioritize the 3D sources in the list sorting, so that I don't have to look through the long list manually.

To find 3D sources, maybe we could search with regex `^(.*[^a-zA-Z\d]+)?3(d|D)([^a-zA-Z\d]+.*)?$`

**Comment by TheBeastLT** [comment]
Hi, there's no easy way to add this with what's currently implemented. IMO this is a pretty niche request, so I don't think that it will be added.
