### ISSUE TITLE
Torrentio addon fail to list so many 4k links 

### ISSUE THREAD

**Issue by krishne35** [TheBeastLT/torrentio-scraper#41]
In torrentio addon it fail to list many 4k links which are present on both RD and rarbg  
![Screenshot_20220228-210858_Chrome Beta](https://user-images.githubusercontent.com/35328770/156012202-97608d01-4119-48f4-9856-8952881d4e93.png)
![Screenshot_20220228-211001_Stremio](https://user-images.githubusercontent.com/35328770/156012226-3204bc59-1511-44d6-80c8-b29057ed769a.png)
![Screenshot_20220228-211116_Chrome Beta](https://user-images.githubusercontent.com/35328770/156012506-ac437c4f-bc2f-4e71-ad80-1ae7030c4e0e.png)

**Comment by TheBeastLT** [comment]
Hi, Torrentio filters out low seeded torrents as is in this case. This torrent has 1 seeder (checked on Feb 26th) and there are more than 10 torrents with >1 seeds for this entry, so it's not displayed to avoid overflooding results with dead torrents.

**Comment by krishne35** [comment]
but its there on RD so is it posible to prevent the filtering when usin rd ???

**Comment by TheBeastLT** [comment]
RD has nothing to do with number of results
Torrentio just adds torrents to RD it does not search for them there (that would take longer and is a niche use case not worth the complexity added). There's a possibility to view your files on RD by going to Discover -> Other -> Real Debrid

**Comment by krishne35** [comment]
No, what i was saying is if we give rd api to torrentio let it not filter out low seed torrents 
Coz most of them already be cached 

Problem with Discover > other > RD it won't sync with continue watching or traktv which is a bummer

**Comment by krishne35** [comment]
Any update regarding this ?

**Comment by TheBeastLT** [comment]
I can increase the number of torrents returned of 1 seed torrents. Maybe that will help a bit, but atm I don't want to allow returning all available torrents with 0 seeds and checking cache availability of them in derbrid as that might spam their servers too much and lead to problems (for most movies there's > 200 torrents available).

**Comment by krishne35** [comment]
Thank you :)
