### ISSUE TITLE
Privacy issue with RD users' API tokens and movie requests sent in cleartext

### ISSUE THREAD

**Issue by doingodswork** [TheBeastLT/torrentio-scraper#5]
Hi fellow Stremio addon developer,

You seem to use proxies for the requests to RealDebrid, according to this code:
https://github.com/TheBeastLT/torrentio-scraper/blob/2eefdc76ec61def92d67ff99d09ecbcf8bdb0439/scraper/moch/realdebrid.js#L73

Looking at the proxy code, you're using HTTP proxies instead of HTTPS proxies, here:
https://github.com/TheBeastLT/torrentio-scraper/blob/33d9921179458585b137d07d053968b587883b4c/scraper/lib/request_helper.js#L14

This means that at least between the node where your addon runs and the node where the proxy runs, but potentially even until the node where RealDebrid runs, the HTTP requests will *not be encrypted*. Every node that's part of a hop (make a `traceroute` to your proxy and to RealDebrid and you'll see it's *many*) will be able to see the full requests in cleartext, including the users' API tokens, the requested magnet URLs and later the returned HTTP stream URL, which usually includes the movie name.

A malicious node, or even just a node of some infrastructure provider that collaborates with some anti-piracy agency or a law firm that's eager to sue RealDebrid users (which has happened in the past) can collect this information and use it against the user. For a law firm with an order by a movie company it can be easy (depending on the country) to get a court order for RealDebrid to hand over the user's email address and IP address (from his initial signup, later logins, charging of RD points etc. - not from your addon, and the chance is high that the user doesn't use a VPN because 1. most users use RD *instead* of a VPN and 2. RD blocks many VPNs so most user's *can't* use their VPN to access RD). Then the only step left is asking the ISP for the user's real identity, including name, address etc.

=> You should switch to an HTTPS proxy, or at least clearly communicate to your addon users that their data is being sent through the net in cleartext, completely unencrypted.

Correct me if I'm missing something.

Just trying to help a fellow addon dev, cheers 🙂

**Comment by TheBeastLT** [comment]
Thanks for pointing that out, it was known to me, and sadly only http is supported by that proxy, tho will look into it further. And also I did not get your point about the law firms, and how this would impact it, if they are able to get user data directly from RD?
