### ISSUE TITLE
Torrentio acting weird 

### ISSUE THREAD

**Issue by eSkRo32** [TheBeastLT/torrentio-scraper#53]
Hi and thanks for your work.

Often, Torrentio doesn't find Any RD cached torrent sources for movies it did before earlier in the day. I have no idea why? So I can't watch the movie anymore... 

Also, sometimes stremio says * 1 addon loading
But it's stick there... Torrentio doesn't load...

I'm on Android TV (NVIDIA SHIELD TV)

**Comment by TheBeastLT** [comment]
Hi @eSkRo32 All seems fine, must be something on your side. Check that your ISP is not blocking Torrentio. Also check that you don't have multiple Torrentio configurations installed (Addons -> My Addons) and leave just one, since there's rate limiting per IP.

**Comment by eSkRo32** [comment]
Hi, Rate you mean? 
I configured Torrentio to show ALL results per quality.. Is that m'y issue?

**Comment by TheBeastLT** [comment]
> I configured Torrentio to show ALL results per quality.. Is that m'y issue?

Check that you have only on `Torrentio` addon entry installed when going to `Addons -> My Addons`

**Comment by eSkRo32** [comment]
Hi, yes, only 1 entry in my addons...
Is there a limit of links Torrentio shows me per day?
Is that what you mean by rate?
Because i've set it to show ALL results per quality. 
Maybe i reached max links showed per day? 
Thx

**Comment by TheBeastLT** [comment]
If you use it normally then you should reach that limit, you can do 300 requests to torrentio per hour.
Can you share some screenshots for which movies you get less stream options than before?

**Comment by eSkRo32** [comment]
I think that that's my issue then.
I didn't know about the 300 request per jour rate.
I'll reconfigure Torrentio to show me 7 results per quality.
And only find 4k/1080P links
That way I won't reach that 300 links per hour.

**Comment by TheBeastLT** [comment]
@eSkRo32 it does not count returned links, it counts the request you make - when you click to get results for a movie/episode that's one request.

**Comment by eSkRo32** [comment]
Ok well
They are already excluded.
Then, I'm puzzled...
There's no way I clicked on 300 + movies or tv shows in an hour....
So, I don't know what's causing this.... 🤔
Maybe Torrentio is acting weird when I set it to show ALL results per quality...

**Comment by eSkRo32** [comment]
Just came back from work

First, Torrentio Just disappeared from addons list.
I had to re-install it...
??? 

And There's no way I requested 300 movies or tv shows
In barely 30 minutes 
And this happens, it says * 0 addons loading *
screenshots attached
![20220513_235045](https://user-images.githubusercontent.com/17524629/168409796-bfc6c2df-7a8e-4b65-935a-15f8f8b65060.jpg)
![20220513_235007](https://user-images.githubusercontent.com/17524629/168409797-eaa38487-5344-4b3c-85e9-cf49831df8c3.jpg)

Note that these 2 movies did return links when I came back from work like 30 minutes ago.... But now nothing... 
And it's not Just these 2, it's ALL... Since the addons is not loading

**Comment by TheBeastLT** [comment]
That's not addon related, something is wrong with your setup. I'd suggest to create a stremio account an try to setup everything on PC and then login with the same account o your TV.
