### ISSUE TITLE
No links! 

### ISSUE THREAD

**Issue by krishne35** [TheBeastLT/torrentio-scraper#59]
Since yesterday the addon is failing to fetch links
Something to do with stremio or torrentio not clearly known 
Series works fine to certain point

**Comment by ExplosiveOtter** [comment]
Yup, can confirm the scraper is having issues. Sometimes it works but for the most part its not fetching any links (neither free nor debrid). @TheBeastLT 🙏

**Comment by TheBeastLT** [comment]
There were some sporadic problems with RD servers, not with Torrentio, but it seems better now.

**Comment by krishne35** [comment]
Thank you

**Comment by krishne35** [comment]
Btw is it possible to scrap rd cloud for links before scraping for other websites like it's implemented on Ezra kodi addon ?
