### ISSUE TITLE
How can run this addon locally

### ISSUE THREAD

**Issue by Nicohidalgo** [TheBeastLT/torrentio-scraper#62]
Hi, I have some troubles trying to run this addon locally, I tried 'npm start -- --launch' and 'node index.js' and I got this error

_"[ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined"_

![image](https://user-images.githubusercontent.com/45693668/179419532-b3b1bf7b-4bbb-4840-8ade-bc23f4368803.png)

**Comment by TheBeastLT** [comment]
This addon needs a db of scraped entries and without it it's useless. So sadly it doesn't make sense running this locally.

**Comment by RageshAntonyHM** [comment]
@TheBeastLT 

Can you please provide that or way to access it ?
