### ISSUE TITLE
Is it possible that torrentio supports more than 1 service like realdebrid?

### ISSUE THREAD

**Issue by Root-FTW** [TheBeastLT/torrentio-scraper#63]
Is it possible that torrentio supports more than 1 service like realdebrid?

I currently have 3 services:

- RealDebrid
-AllDebrid
- Premiumize

I would like to be able to put my 3 services at the same time in torrentio, but it only allows me 1

**Comment by TheBeastLT** [comment]
Yes, it's possible. There are two ways that produce different results:
- Configure all 3 in one installation, by selecting another debrid service from the drop down after entering previous one, it will create a configuration of all debrid services with an api key configured. With this way then it will respond with cached streams from the first service it finds it in. Ie you have A, B, C streams and RD, PM configured. RdD has just A stream cached and PM has A and C streams. So it will return RD link for A stream and PM link for C stream (and download to debrid link for B stream for both debrids if enabled)
- You can install 3 different configurations of torrentio each having different debrid client. This way it will return all links that are available on each debrid site separately , even some are already available on another. Just note that this will do 3 requests on each movie/episode selection when searching for streams and there is a rate limit of 300 requests per hour.

**Comment by Root-FTW** [comment]
> Yes, it's possible. There are two ways that produce different results:
> 
> * Configure all 3 in one installation, by selecting another debrid service from the drop down after entering previous one, it will create a configuration of all debrid services with an api key configured. With this way then it will respond with cached streams from the first service it finds it in. Ie you have A, B, C streams and RD, PM configured. RD has just A stream cached and PM has A and C streams. So it will return RD link for A stream and PM link for C stream (and download to debrid link for B stream for both debrids if enabled)
> * You can install 3 different configurations of torrentio each having different debrid client. This way it will return all links that are available on each debrid site separately , even if some are already available on another. Just note that this will do 3 requests on each movie/episode selection when searching for streams and there is a rate limit of 300 requests per hour.

@TheBeastLT thanks for the detailed explanation, and I took some valuable learning with me, I didn't know that you could only make 300 requests per hour, that explains a lot of things :O 


Thank you for making Torrentio so great.

I hope one day you enable your profile to make donations, or a link to ko-fi.com, you certainly deserve them

**Comment by TheBeastLT** [comment]
> ... I didn't know that you could only make 300 requests per hour, that explains a lot of things :O

Yes, this is to prevent abuse of the addon, and 300 requests in an hour sounds a reasonable limit and should be enough to decide on what to watch. Let me know if you've hit these limits, maybe they could be increased up to 500-600 if necessary.

**Comment by Root-FTW** [comment]
> > ... I didn't know that you could only make 300 requests per hour, that explains a lot of things :O
> 
> Yes, this is to prevent abuse of the addon, and 300 requests in an hour sounds a reasonable limit and should be enough to decide on what to watch. Let me know if you've hit these limits, maybe they could be increased up to 500-600 if necessary.

@TheBeastLT 
I think so, I have reached that limit, since it has reached the point where clicking on a torrent movie no longer shows me any results, and I have realized that if I wait for the next day it works again.

I like to watch a lot of movies, during the week I only see 2 movies per day, but on the weekend I can see up to 5, and to decide those 5 I am clicking on many movies and checking many links (looking for which link says it has 5.1 audio) until I like one and see it

In my very particular case, maybe it would be great to increase the requests to 1,000 a day, but I don't think everyone uses as much torrent as I do hehe

**Comment by TheBeastLT** [comment]
> In my very particular case, maybe it would be great to increase the requests to 1,000 a day, but I don't think everyone uses as much torrent as I do hehe

These limit are per hour, the next hour they refresh again for 300 requests. Also check that you don't have too many torrentio configurations installed, since each one does one request.

**Comment by coolspot18** [comment]
It seems that results are returned by order in the list? If I configure multiple Debrid services, the plugin seems to favor Real-Debrid which I believe is higher up in the Debrid service drop down box?

**Comment by TheBeastLT** [comment]
@coolspot18 you can potentially achieve this by manually modifying the addon install url after configuring it. You need to put `alldebrid=xxx` before `realdebrid=xxx` in the url.
Ie.: `https://torrentio.strem.fun/alldebrid=xxxx|realdebrid=xxxx/manifest.json`

**Comment by Cmai7385** [comment]
Hi

I tried installing torrentio twice as suggested.  Once with RD added and then with AD added.  But the second installation superceded the first.  Now I only have AD.   Please advise.   Thank you
