### ISSUE TITLE
Torrentio + Put.io not working correctly

### ISSUE THREAD

**Issue by bitsper2nd** [TheBeastLT/torrentio-scraper#65]
## Summary
Hi I'm trying Put.io through the Torrentio addon for Stremio. It is not playing the video in the app. So far I tested this on Android phone and a Shield TV.

- My sources are Cinema for movies and series. Animekitsu for japanese cartoons.
- My providers are RARGB, Nya and Put.io

![image](https://user-images.githubusercontent.com/22452474/181395728-e25577a9-ffc1-4f81-997e-161b6c17489d.png)

![stremio](https://user-images.githubusercontent.com/22452474/181396440-34cb445d-a262-4c9d-84b7-712a5c6d1a9b.jpeg)

## The Problem
Every time I try to watch a video on stremio, I get an error. 

![play](https://user-images.githubusercontent.com/22452474/181396436-020a8665-4bed-41df-aa20-afecd1789bf8.jpeg)

![error](https://user-images.githubusercontent.com/22452474/181396437-f88cf6d1-c06b-42d6-af07-3a0f05d924e1.jpeg)

The file does gets downloaded in Put.io, but I can't play it on Stremio.

![image](https://user-images.githubusercontent.com/22452474/181396785-f6347d1b-54ad-4305-bb41-3a3c78ccc0cd.png)

I don't know if this is problem with Put or with Torrentio? I have my App configured like this on Put.io:

![image](https://user-images.githubusercontent.com/22452474/181395806-b52fa613-9981-4556-9fb9-a3945d5ea6fb.png)

Any solution for this?

**Comment by TheBeastLT** [comment]
Hi @bitsper2nd, putio integration atm is only working partially, since putio removed permissions for public link generation for user created apps. Contact me on discord (through Stremio discord), there might be a possible improvement if you still want to use putio.
