### ISSUE TITLE
Every day torrentio scrapes realdebrid?

### ISSUE THREAD

**Issue by Root-FTW** [TheBeastLT/torrentio-scraper#66]
Every day I upload torrents to my realdebrids account, but I have realized that in stremio with the torrentio addon they are not shown, so the next day I check to see if they already come out:

I would like to know if realdebrid torrentio scrapes daily, and if it does it daily, what time does it do it? so I could schedule my script at the right time.

(I use a script in python "https://github.com/mishpajz/RDRSS" to which I assign an RSS source of torrents that interest me, and I run it daily at 8am pacific time)

**Comment by TheBeastLT** [comment]
Torrentio doesn't scrape realdebrid, it's not possible to scrape any of the debrid services. Torrentio scrapes providers mentioned in the configuration page.
You can view your personal realdebrid catalog via discover screen and selecting `Others -> Real Debrid`
