### ISSUE TITLE
[Feature Request] Option to search in RealDebrid Torrent Cloud

### ISSUE THREAD

**Issue by shscs911** [TheBeastLT/torrentio-scraper#69]
## Issue Type
* Feature Request

## Description
* Sometimes, a user adds a torrent, not present in Torrentio buit-in Torrent Providers, but which can be successfully downloaded by RD. Current way to watch these titles in Stremio, is to play them from `Others - RealDebrid` section. The issue is that, these tiles won't be listed in `Continue Watching` section or integrated with Trakt Scrobbling, if we use this method.

* A feature which enables users to see titles from their Real Debrid Torrent Cloud (https://real-debrid.com/torrents), in additon to the ones sourced out from the Torrent Providers configured in Torrentio, when searching for a Movie / TV Show.
(Syncler+ has a feature where it searches RD Cloud, in addition to the Providers in Provider Packages, but the scraping process takes too long)

* It may be implemented as an option in `Debrid options` in Torrentio configuration, if scraping RD Cloud slows down the entire scraping process.

* Is it possible to implement such a feature in Torrentio or is it something that requires making changes to Stremio itself?

**Comment by Root-FTW** [comment]
please make that posible !!!

**Comment by TheBeastLT** [comment]
This won't be added, since it would make too many requests to RD API from torrentio server, which might get it blocked. Also it would be difficult to match titles from name, since it can take time, so it would make the addon less responsive.
As you've mentioned it's possible to use the catalog from others. Regarding it not being part of continue section, maybe it should be possible to change the type from other to smth else, so it would appear there.

**Comment by shscs911** [comment]
@TheBeastLT 
That makes sense. Hammering the RD API will be bad and I'd hate for Torrentio to get blocked because of that. That and Title matching might be one of the reasons why Syncler+ is so slow in resolving the links, whereas Torrentio+Stremio resolves them near instantaneously (Thanks for that, btw).

Can you explain a bit more about changing the media type to something else, to make it appear in the `Continue Watching` section? How does Stremio differentiate between titles from RD and the ones from Stremio/Trakt catalogue?
