### ISSUE TITLE
New providers

### ISSUE THREAD

**Issue by ravtakhar** [TheBeastLT/torrentio-scraper#7]
Hey,

More of a feature request but wondering if there is anyways to increase the max connections on the Android APK. I tried to get a hold of the Android source but apparently it's closed source :/

Additional providers:
https://www.torrentdownloads.me/
https://www.limetorrents.info/
https://pirateiro.com/
https://zooqle.com/
https://yts.mx/
https://katcr.to/
https://torrentz2.is/
https://www.torlock.com/
https://eztv.ag/

I have also noticed some weird behavior. When I start a link using TPB+ it'll load but loading the same torrent using torrentio it'll get stuck? Not as important as it works 90% of the time but it is something I have noticed this week.

Thank you!

**Comment by TheBeastLT** [comment]
Hey, addons cannot influence any client settings or machine. It only return information from where to download the content.
If it's the same torrent (infoHash is the same) there should be no difference in their downloading behavior as addons cannot influence that.

Regarding the providers some of them are already indexed (eztv, yts, kat) and most of the other sites are also torrent site aggregators, but I'll look into those which have unique content.
I have other providers to add on the backlog, but until then a have other stuff to do regarding indexing and categorization, but as it's summer time is short.

**Comment by ravtakhar** [comment]
Thank you for the consideration! I thought it would be worth a shot trying to get the max connections up...

The best add-on for Stremio thanks for your contribution 👍

**Comment by radiomaniac** [comment]
Hi, I sent you a message on reddit before I realized you had a github page, so I better ask the question around here, sorry if I bothered you. I'm writting it inside this feature request as it's about the same topic.

I'd like to add a spanish (Spain variety) torrent provider for my mom who doesn't speak English. Could you consider adding this one?

https://dontorrent.one/

In my reddit message I suggested another one that also has latin american spanish, but then I found the top one which only has Spain's variety of Spanish torrents, so figured out there would be less filtering required. In any case, the one I suggested is this one:

https://www.elitetorrent.com/

In case you also want to add some latin american spanish provider support.

You're amazing man, thanks a lot! Let me know if you have some paypal donation link or something!

**Comment by TheBeastLT** [comment]
Hi @radiomaniac, currently I'm not looking in adding new torrent providers, as now it's mostly in maintanance mode (fixing bugs, improving indexing, some manual checking for anime indexing).
But I'll have this in mind when I'll be adding new features/providers.

**Comment by radiomaniac** [comment]
> Hi @radiomaniac, currently I'm not looking in adding new torrent providers, as now it's mostly in maintanance mode (fixing bugs, improving indexing, some manual checking for anime indexing).
> But I'll have this in mind when I'll be adding new features/providers.

No worries, thanks anyways, I'll check in the future in case you add it.

But now that you mentioned that, I noticed something in the Android tv version of the app. Whenever I watch something it stays in the recently watched shows and I can't remove it from there unless I use my phone as a mouse, and click at the right place. There doesn't seem to be a way of doing that using the remote control.

Thanks again!

**Comment by TheBeastLT** [comment]
> No worries, thanks anyways, I'll check in the future in case you add it.
> 
> But now that you mentioned that, I noticed something in the Android tv version of the app. Whenever I watch something it stays in the recently watched shows and I can't remove it from there unless I use my phone as a mouse, and click at the right place. There doesn't seem to be a way of doing that using the remote control.
> 
> Thanks again!

That's something not addon related. Everything related to UI and interactions should be brought up to stremio developers as feature requests or bugs.

**Comment by radiomaniac** [comment]
> > No worries, thanks anyways, I'll check in the future in case you add it.
> > But now that you mentioned that, I noticed something in the Android tv version of the app. Whenever I watch something it stays in the recently watched shows and I can't remove it from there unless I use my phone as a mouse, and click at the right place. There doesn't seem to be a way of doing that using the remote control.
> > Thanks again!
> 
> That's something not addon related. Everything related to UI and interactions should be brought up to stremio developers as feature requests or bugs.

Understood!
