### ISSUE TITLE
The entire stremio community detected an error in torrentio

### ISSUE THREAD

**Issue by Root-FTW** [TheBeastLT/torrentio-scraper#73]
2 days ago the 3rd chapter of house of dragons was released, and torrentio is the only addon that does not show sources to see it.

Torrentio is the most used addon to view content, and this weekend it didn't work, the whole community is experiencing the same thing.

https://www.reddit.com/r/StremioAddons/comments/x6603d/no_streams_were_found_ep3_house_of_dragon/

More:
https://www.reddit.com/r/Stremio/comments/x6e8h0/is_it_normal_that_torrentio_sometimes_doesnt_give/

https://www.reddit.com/r/StremioAddons/comments/x6lq2f/addons_torrentio_rarbg_and_few_more_not_working/

https://www.reddit.com/r/StremioAddons/comments/x6la2z/torrentio_not_able_to_find_stream_for_third/

https://www.reddit.com/r/StremioAddons/comments/x6s5ls/the_first_time_i_was_disappointed_with_the/

https://www.reddit.com/r/StremioAddons/comments/x6oun0/no_streams_found_for_rick_and_morty_season_6_ep_1/

https://www.reddit.com/r/Stremio/comments/x6wh88/house_of_dragon/

https://www.reddit.com/r/Stremio/comments/x6x2nc/no_torrent_links_for_house_of_dragon/

https://www.reddit.com/r/StremioAddons/comments/x6ydco/house_of_dragons/

**Comment by ciwy85** [comment]
Looks like it has been resolved now.
