### ISSUE TITLE
Torrent from similarly named TV Show, "Space: 1999" showing up in the list for "Spaced"

### ISSUE THREAD

**Issue by mattalexx** [TheBeastLT/torrentio-scraper#78]
Not sure if this is correct place to report data problems, but here goes:

In the list of streaming options for S01E01 of [Spaced](https://www.imdb.com/title/tt0187664/) (1999–2001), I'm getting an option that references [this torrent](https://www.1377x.to/torrent/4800255/Space-1999-All-Seasons-1080p-BluRay-x265-by-Kamey/), which is from another show, called [Space: 1999](https://www.imdb.com/title/tt0072564/) (1975–1977).

![Screenshot](https://i.imgur.com/hVwHT09.png)

https://app.strem.io/shell-v4.4/?#/detail/series/tmdb:745/tt0187664:1:1

**Comment by TheBeastLT** [comment]
Should be fixed once the caches expire
