### ISSUE TITLE
Advanced filters

### ISSUE THREAD

**Issue by ciwy85** [TheBeastLT/torrentio-scraper#79]
First of all great work on the addon,  much appreciated. Can I suggest adding a more advanced filters I understand you don't want to add more complexity for the users but maybe advanced settings for some users could show up after ticking a box at the configuration screen. I have noticed requests on discord asking for Dolby Vision and HDR filters for people whose devices don't support it,  even my shield Pro has difficulties with some DV files. Most of the file names do have this information included obviously it's not bulletproof but better then nothing. Another filter is a max bitrate for people with slower broadband speeds. This cold be calculated with the length of the movie and the size, again it wouldn't be 100% accurate but I know other apps are doing it that way with great success. Last thing is to move all filtered files at the very bottom of the results so even if something gets wrongly filtered out we would still have access to it.

**Comment by TheBeastLT** [comment]
> I have noticed requests on discord asking for Dolby Vision and HDR filters for people whose devices don't support it, even my shield Pro has difficulties with some DV files. Most of the file names do have this information included obviously it's not bulletproof but better then nothing. 

This was recently added. See https://github.com/TheBeastLT/torrentio-scraper/issues/67

> Another filter is a max bitrate for people with slower broadband speeds. This cold be calculated with the length of the movie and the size, again it wouldn't be 100% accurate but I know other apps are doing it that way with great success. 

Getting duration would be very complicated and not sure if it would bring any value. You can already determine this based on the size, since all streams for same movie/episode will have almost the same duration, so only the size is different.

> Last thing is to move all filtered files at the very bottom of the results so even if something gets wrongly filtered out we would still have access to it.

That's not what filtering/excluding should do.
