### ISSUE TITLE
Hunted AU showing for Hunted

### ISSUE THREAD

**Issue by v3euk** [TheBeastLT/torrentio-scraper#81]
Hi,
The series Hunted shows episodes for Hunted AU for season 1. The standard season 1 is available on RARBG. Not sure if issues like this should be flagged here or is this anything that can be done myself to prevent this?

![FA0A611D-8721-4A73-999A-575B08A3A256](https://user-images.githubusercontent.com/62473149/196361403-8aa01483-c9ad-4fab-a1ce-14da09afd58e.png)

![42D0F39D-1E3E-469B-87D7-BD9214734A4B](https://user-images.githubusercontent.com/62473149/196361619-35699343-4ca7-4cea-9f68-864c6a5bdd0f.jpeg)

**Comment by TheBeastLT** [comment]
Should be fixed, once caches expire. Automatic indexing is not always correct, especially when titles have the same name.
