### ISSUE TITLE
Torrent from "Nix" showing up in the list for "Don't Worry Darling"

### ISSUE THREAD

**Issue by mattalexx** [TheBeastLT/torrentio-scraper#82]
In the list of streaming options for [Don't Worry Darling] (2022), I'm getting an option that references [Nix] (2022).

![Screenshot](https://i.imgur.com/f23erO4.png)

https://www.strem.io/s/movie/dont-worry-darling-10731256

[Don't Worry Darling]: https://www.imdb.com/title/tt10731256/
[Nix]: https://www.imdb.com/title/tt14292086/

**Comment by TheBeastLT** [comment]
Should be fixed, once the caches expire, thanks.
