### ISSUE TITLE
New sorting methods

### ISSUE THREAD

**Issue by O3nboi** [TheBeastLT/torrentio-scraper#85]
Might I suggest that you provide some alternative sorting methods to the torrentio addon?

My most pressing request would be sorting by the number of seeders divided by the file size. This would effectively tell you how fast you can stream something.
Other suggestions include:

- Inverse Size (small to big)
- Inverse Quality (bad to good)
- Inverse Size then quality (Shows high quality but small streams)

**Comment by TheBeastLT** [comment]
I don't see value in such sorting options, seems like they would have very niche and little value for users
