### ISSUE TITLE
Some links doesn't show up until a day or days later

### ISSUE THREAD

**Issue by tinnyskillz** [TheBeastLT/torrentio-scraper#89]
The addon pulls many links, but it doesn't pull every link from each torrent site selected from the initial setup. Some links doesn't show up until a day or days later.

Also it would be nice if we could get a size/bitrate limit option, a HDR/Dolby Vision priority setting, a format priority option (prefer MKV over MP4 for example), maybe Seren/Fen/Umbrella from Kodi sources etc. There's so many things that would make the addon even better.

**Comment by TheBeastLT** [comment]
Torrent sites are scraped roughly every 4 hours, and also result are heavily cached on each request, so it can take up 8 hours for new episodes to appear. Tho usually it's quicker.

The addon is great as is, and I don't want to increase complexity and config options, which would lead
