### ISSUE TITLE
Torrentio Links do not seem to work

### ISSUE THREAD

**Issue by nperez0111** [TheBeastLT/torrentio-scraper#9]
Me and a few other people [on Reddit](https://www.reddit.com/r/StremioAddons/comments/i86avk/are_torrentio_links_not_working_for_anyone_else/) are having trouble with Torrentio in the past couple of days.

Could you maybe check your hosting to see what may be going on? If not I'd be willing to put up a seedbox of my own to balance between.

**Comment by TheBeastLT** [comment]
Hi, it seems it's related to proxy used for realdebrid requests. Some of the proxy hosts seem to freeze up. I'll try to investigate and for now I've added a timeout so that not all requests would fail and remove identified slow proxy hosts.

**Comment by nperez0111** [comment]
Thanks for your response. That's good to hear you identified the issue. One thing has me wondering, should real debrid being down have any effect on the torrent links I was receiving? Maybe they were just bad torrents?

**Comment by TheBeastLT** [comment]
Links without the `[RD+]` prefix are not affected by real debrid. Just the torrent's infohash is returned, which is then used by stremio's local server to stream that torrent.
