### ISSUE TITLE
Request to add links in Spanish (Latin America) language.

### ISSUE THREAD

**Issue by DallasBelt** [TheBeastLT/torrentio-scraper#94]
Is it possible that the addon could scrape links in Latin American Spanish?

**Comment by TheBeastLT** [comment]
Duplicate of #72

**Comment by DallasBelt** [comment]
I'm sorry to revive this issue, but #72 gives links in Spanish from Spain (Castellano). There is cinecalidad.run which contains links in Latin American Spanish (Mexico). Could it be possible to add it to Torrentio?

Thank you.
