### ISSUE TITLE
Request - Just want to know if it's possible to add YGGtorrent as provider for french content. 

### ISSUE THREAD

**Issue by daniwalter001** [TheBeastLT/torrentio-scraper#96]
YGGTORRENT is the best when it come to french content. Their new url is https://yggtorrent.lol.

Thanks

**Comment by TheBeastLT** [comment]
No, it's a private tracker. For French content you already have Torrent9.

**Comment by daniwalter001** [comment]
Okay. Is it impossible for private provider to be added?

**Comment by TheBeastLT** [comment]
It's possible, but then it can no longer be a public addon, since then it would need credentials for the provider, and torrentio only deals with public ones. Look into jackett addon if you want private trackers.

**Comment by daniwalter001** [comment]
Thanks 👍

**Comment by razeNFR** [comment]
@daniwalter001 you founded a solution since ?

**Comment by razeNFR** [comment]
Je sais pas pourquoi je parle anglais alors que tu es sûrement Français, j'aimerais pouvoir essayer jackett mais impossible d'aller sur l'url pour récupérer la clé d'api de jackett, est-ce que tu aurais Discord pour m'aider un peu ? 

Mon Discord : razenfr

**Comment by daniwalter001** [comment]
Je suis francophone également. Je t'écris sur discord

**Comment by Kwixotic** [comment]
Salut, est ce que un de vous à réussi a trouver une solution pour intégrer yggtorrent sur stremio ?
