### ISSUE TITLE
Subtitle files from inside torrents not available on Android TV 

### ISSUE THREAD

**Issue by nblondiau** [TheBeastLT/torrentio-scraper#98]
Streaming from the same magnet link on multiple clients.

Windows: subs available
Android: subs available
Android TV: subs list not populated

**Comment by TheBeastLT** [comment]
This is not in any way related to torrentio. You probably have some missing subtitles addons in your Android TV setup.

**Comment by nblondiau** [comment]
I'm not using any subtitles addon, and the addons are synced to the same account on every devices.

**Comment by TheBeastLT** [comment]
Like I said, this is NOT related to Torrentio, as this addon does not control subtitles in anyway. This is some issue in your setup (or you misunderstood how something works). Please do no reopen.
